### PR TITLE
:bug: (modals) allow content to be vertically scrollable

### LINKED ISSUE #3079: [Bug]: Modals not enabling scrolling when contents overflow
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Steps to reproduce:
1. Open a big modal e.g. Import transactions modal
2. Resize the browser window to smaller size
image

The behavior should be for the modal to enable scrolling when its contents overflow

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by MatissJanis**
Closes #3079

### CODE REVIEW

**Comment by matt-fidd** [comment]
The scrollbar is showing for me when there is no overflow

image

image

**Comment by MatissJanis** [comment]
Thanks @matt-fidd ! Should be better now (once the preview build compiles).

**Review by matt-fidd — DISMISSED** [review]

**Comment by joel-jeremy** [comment]
Looks good! Can we apply the scrollbar style to match the other scrollbars in the app?

**Comment by MatissJanis** [comment]
> Looks good! Can we apply the scrollbar style (`styles.darkScrollbar`/`styles.lightScrollbar`) to match the other scrollbars in the app?

We already have those styles applied: https://github.com/actualbudget/actual/blob/58eeee825ea441657db7c58754014fff7de214c1/packages/desktop-client/src/components/common/Modal2.tsx#L117

Are they not showing up for you? Mac looks good.

**Comment by youngcw** [comment]
Im not seeing any scrollbar styling.  Also the bottom scrollbar is always showing for me

**Comment by MatissJanis** [comment]
Can someone take over this PR from me? I don't have a Win/Linux machine, so debugging it is not really possible on my end.

File: packages/desktop-client/src/components/common/Modal2.tsx [hunk 1]
```diff
@@ -87,7 +88,10 @@ export const Modal = ({
     >
       <ReactAriaModal>
         {modalProps => (
-          <Dialog aria-label="Modal dialog">
+          <Dialog 
+            aria-label="Modal dialog"
+            className={`${css({ ...styles.lightScrollbar })}`}
```
Comment (MikesGlitch) [inline packages/desktop-client/src/components/common/Modal2.tsx:93]: image

The issue was because the styling includes the ```&``` combinator

File: packages/desktop-client/src/components/common/Modal2.tsx [hunk 2]
```diff
@@ -87,7 +88,10 @@ export const Modal = ({
     >
       <ReactAriaModal>
         {modalProps => (
-          <Dialog aria-label="Modal dialog">
+          <Dialog 
+            aria-label="Modal dialog"
+            className={`${css(styles.lightScrollbar)}`}
```
Comment (MikesGlitch) [inline packages/desktop-client/src/components/common/Modal2.tsx:93]: The issue was because the styling includes the ```&``` combinator

Should be fixed now:

 image

**Review by jfdoming — APPROVED** [review]
I don't have a Windows computer on hand but looks good on Android and on Mac OS (both scrolling).

**Review by matt-fidd — DISMISSED** [review]
Checked on Windows, looking good.

**Comment by twk3** [comment]
Chrome in linux, only shows when needed, but introduces a bottom scrollbar at the moment
Screenshot from 2024-08-01 07-43-21



Firefox in linux looks good.

**Comment by MatissJanis** [comment]
LGTM on my end (Mac)!

How's it looking on Win/Linux? Need final approvals to merge.

**Comment by matt-fidd** [comment]
All looking okay on Windows, the visual bug in the schedules modal has gone too (tested previous commit vs newest to make sure).

**Review by joel-jeremy — APPROVED** [review]
Looks good on my end! :)

**Review by twk3 — APPROVED** [review]
Looking good on linux
