### PR TITLE
Fix currencyToAmount incorrectly converting input

### LINKED ISSUE #4277: [Bug]: rules: amount smaller than 10 multiplies with 10 when decimal separator is not "."
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

I tried to create a new rule with condition "amount = 3,80". As I’m German, I’m using the comma instead of period as the decimal separator. I have set up Actual to use the German number format 1.000,00 instead of the default 1,000.00. When I set up the rule, 3,80 is multiplied to 38,00 on save, or when I press return. The bug does not occur with the default number format. 

https://github.com/user-attachments/assets/2e65ae31-4ef3-4bf8-bd6d-9f131bcfb1ac

### How can we reproduce the issue?

How can we reproduce the issue?

- Set your number format to ˋ1.000,00ˋ
- create a new rule
- set condition ˋamount = 3,80ˋ
- press return

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Safari

### Operating System

iPad OS

### PR DESCRIPTION
**Pull request by AntoineTA**
Fixes #4277

The issue described there arises because the `currencyToAmount()` utility function expects a string representing an amount in the current number format (dot-comma in this case). However, at some point during the update, the function is passed a string where the decimal separator is represented with a dot. This causes the function to ignore the decimal separator when converting the string to the exact amount.

The fact that `currencyToAmount()` expects a string in the current number format also causes other unintended behaviour.
- In some cases, if the user does not use the decimal separator defined by their number format when entering an amount, the separator will be ignored. For example, when using comma-dot format, the input `1,83` will be saved as `183.00`.
- Similarly, if the user does not use the expected separator when searching for an amount, the search will yield no result.

This PR solves these issues by making sure `currencyToAmount()` is able to handle any currency string, not just those in the format configured by the user.

### CODE REVIEW

**Review by youngcw — DISMISSED** [review]
This seems to be working well in everything Ive thrown at it.  This should have multiple approvals where its pretty far reaching.

File: packages/loot-core/src/shared/util.ts [hunk 1]
```diff
@@ -283,47 +283,44 @@ export function getNumberFormat({
...
-      regex = /[^-0-9.]/g;
-      separator = '.';
+      thousandsSep = ',';
+      decimalSep = '.';
   }
 
   return {
     value: format,
-    separator,
+    thousandsSep,
```
Comment (joel-jeremy) [inline packages/loot-core/src/shared/util.ts:318]: Small nit:
```suggestion
    thousandsSeparator,
```

File: packages/loot-core/src/shared/util.ts [hunk 2]
```diff
@@ -283,47 +283,44 @@ export function getNumberFormat({
...
+    decimalSep,
```
Comment (joel-jeremy) [inline packages/loot-core/src/shared/util.ts:319]: Small nit:
```suggestion
    decimalSeparator,
```

**Comment by joel-jeremy** [comment]
Made some small suggestions but aside from that, LGTM!

**Comment by AntoineTA** [comment]
> Made some small suggestions but aside from that, LGTM!

Thanks! I made the suggested changes.

**Review by joel-jeremy — APPROVED** [review]
LGTM!
