### PR TITLE
:bug: (mobile) scrolling in lists with pull-to-refresh

### LINKED ISSUE #1699: [Bug]: mobile - scrolling in transaction list and account list
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

On mobile

When you first scroll DOWN in the transaction list or account list the scroll does not happen. You need to scroll down one more time for the scroll to register.

### What error did you receive?

_No response_

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

_No response_

### Operating System

None

### PR DESCRIPTION
**Pull request by MatissJanis**
Closes #1699

### CODE REVIEW

File: packages/desktop-client/src/components/responsive/PullToRefresh.tsx [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+import { css } from 'glamor';
+
+type PullToRefreshProps = ComponentProps<typeof BasePullToRefresh>;
+
+export default function PullToRefresh(props: PullToRefreshProps) {
+  return (
+    <div style={{ overflow: 'auto' }}>
+      <BasePullToRefresh
+        pullDownThreshold={80}
+        resistance={2}
```
Comment (MatissJanis) [inline packages/desktop-client/src/components/responsive/PullToRefresh.tsx:13]: Increasing the resistance a bit in order to make it more difficult to refresh accidentally

File: packages/desktop-client/src/components/responsive/PullToRefresh.tsx [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+        className={String(
+          css({
+            '& .ptr__pull-down': {
+              textAlign: 'center',
+            },
+            '& .ptr__children': {
+              overflow: 'hidden auto',
+            },
```
Comment (MatissJanis) [inline packages/desktop-client/src/components/responsive/PullToRefresh.tsx:21]: This is the main fix.. a bit hacky.. but I couldn't figure out anything better sadly.

File: packages/desktop-client/src/components/responsive/PullToRefresh.tsx [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+  return (
+    <div style={{ overflow: 'auto' }}>
+      <BasePullToRefresh
+        pullDownThreshold={80}
+        resistance={2}
+        className={String(
+          css({
+            '& .ptr__pull-down': {
+              textAlign: 'center',
+            },
```
Comment (MatissJanis) [inline packages/desktop-client/src/components/responsive/PullToRefresh.tsx:18]: Centers the "pull down to refresh" label that is visible before the refresh starts

**Review by joel-jeremy — APPROVED** [review]
