### PR TITLE
Fix filter operator switching behavior

### LINKED ISSUE #7123: [Bug]: Changing Category Group from `is` to `contains` replaces budget with the raw UUID
### What happened?

Trying to change Category Groups from `is` to `contains` populates the input field with the UUID of the Category Group instead of the raw category string.

### How can we reproduce the issue?

Screenshot 2026-03-04 at 10 31 35 AM
Screenshot 2026-03-04 at 10 31 46 AM

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

None

### PR DESCRIPTION
**Pull request by sk10727-a11y**
## Description
Fixes an issue where switching filter operators between exact-match (is, one of) and text-based operators (contains, matches) would populate the input with UUIDs instead of human-readable names.

This PR adds logic to correctly transform values when switching between operator types for ID-based fields (accounts, categories, category groups, payees):
- Single-ID → text: Converts stored ID → text, since there is a one-to-one mapping
- Text → Single-ID: Converts text → ID (if uniquely matched), ensuring correctness without guessing
- Multi-ID → text: If the array size is 1, resolves ID to text (if uniquely matched); otherwise, clears the value, since multiple IDs cannot be reliably represented as a single string
- Text → Multi-ID: Resolves text to a single ID (if uniquely matched) and wraps it in an array, matching the expected multi-value format

**Unique to the accounts filter, there are account no-value operators (is on budget, is off budget):**
- No-value → text: Converts preserved ID(s) → text when possible
- No-value → Single-ID: Converts preserved text → ID when a unique match exists
- No-value → Multi-ID: Resolves preserved text to a single ID (if uniquely matched) and wraps it in an array; otherwise clears the value

**Note:**
- Single-ID exact-match operators: is, is not → store a single ID value
- Multi-ID exact-match operators: one of, not one of → store an array of IDs
- Text-based operators: contains, matches, does not contain → store plain strings
- Account no-value operators: is on budget, is off budget → do not use input values but preserve state for future conversions

This ensures the input always matches the expected format for the selected operator and prevents UUID leakage in the UI.

## Related issue(s)
Fixes #7123.

## Testing
Tested the following transitions across accounts, categories, category groups, and payees:
- is → contains, matches, does not contain: ID correctly converted to text
- is not → text operators: same behavior as above
- contains / matches → is, is not: text converted back to ID when an exact match exists
- contains / matches → one of: text converted to single ID and wrapped in array
- one of / not one of → text operators: prevented invalid conversion (cleared value)
- is → one of: single ID preserved and wrapped in array

**Account-specific cases:**
- is → is on budget / is off budget → contains: correctly converts back to text
- one of → is on budget / is off budget → text: clears or converts appropriately
- text → is on budget / is off budget → is: attempts to resolve back to ID

## How to test
1. Navigate to an account
2. Create or edit a filter on an ID-based field (accounts, category, category group, payees)
3. Switch between operators
4. Verify the input remains human-readable and matches the outlined behavior

## Checklist

- [X] Release notes added (see link above)
- [X] No obvious regressions in affected areas
- [X] Self-review has been performed - I understand what each change in the code does and why it is needed

### Bundle Stats

Bundle | Files count | Total bundle size | % Changed
------ | ----------- | ----------------- | ---------
desktop-client | 34 | 12.93 MB → 12.94 MB (+4 kB) | +0.03%
loot-core | 1 | 4.85 MB | 0%
api | 1 | 3.88 MB | 0%
cli | 1 | 7.91 MB | 0%

<details>
<summary>View detailed bundle stats</summary>

#### desktop-client

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
34 | 12.93 MB → 12.94 MB (+4 kB) | +0.03%

<details>
<summary>Changeset</summary>

File | Δ | Size
---- | - | ----
`src/components/filters/FiltersMenu.tsx` | 📈 +4 kB (+22.96%) | 17.41 kB → 21.41 kB
</details>

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
No assets were added

**Removed**
No assets were removed

**Bigger**
Asset | File Size | % Changed
----- | --------- | ---------
static/js/chart-theme.js | 705.55 kB → 709.55 kB (+4 kB) | +0.57%

**Smaller**
No assets were smaller

**Unchanged**
Asset | File Size | % Changed
----- | --------- | ---------
static/js/index.js | 1.85 MB | 0%
static/js/BackgroundImage.js | 121.09 kB | 0%
static/js/FormulaEditor.js | 814.39 kB | 0%
static/js/PayeeRuleCountLabel.js | 52.12 kB | 0%
static/js/ReportRouter.js | 1.18 MB | 0%
static/js/ScheduleEditForm.js | 136.13 kB | 0%
static/js/TransactionEdit.js | 185.13 kB | 0%
static/js/TransactionList.js | 82.8 kB | 0%
static/js/Value.js | 4.34 MB | 0%
static/js/ca.js | 191.72 kB | 0%
static/js/client.js | 450.92 kB | 0%
static/js/da.js | 104.4 kB | 0%
static/js/de.js | 174.12 kB | 0%
static/js/en-GB.js | 8.2 kB | 0%
static/js/en.js | 176.5 kB | 0%
static/js/es.js | 181.54 kB | 0%
static/js/extends.js | 486.5 kB | 0%
static/js/fr.js | 176.79 kB | 0%
static/js/indexeddb-main-thread-worker-e59fee74.js | 13.46 kB | 0%
static/js/it.js | 165.68 kB | 0%
static/js/narrow.js | 363.68 kB | 0%
static/js/nb-NO.js | 151.58 kB | 0%
static/js/nl.js | 108.66 kB | 0%
static/js/pl.js | 88.34 kB | 0%
static/js/pt-BR.js | 193.49 kB | 0%
static/js/resize-observer.js | 18.06 kB | 0%
static/js/th.js | 178.91 kB | 0%
static/js/theme.js | 30.79 kB | 0%
static/js/uk.js | 212.28 kB | 0%
static/js/useFormatList.js | 9.86 kB | 0%
static/js/wide.js | 292 B | 0%
static/js/workbox-window.prod.es5.js | 7.33 kB | 0%
static/js/zh-Hans.js | 110.19 kB | 0%
</div>
</details>

---

#### loot-core

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
1 | 4.85 MB | 0%

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
No assets were added

**Removed**
No assets were removed

**Bigger**
No assets were bigger

**Smaller**
No assets were smaller

**Unchanged**
Asset | File Size | % Changed
----- | --------- | ---------
kcab.worker.BLXvyUAG.js | 4.85 MB | 0%
</div>
</details>

---

#### api

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
1 | 3.88 MB | 0%

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
No assets were added

**Removed**
No assets were removed

**Bigger**
No assets were bigger

**Smaller**
No assets were smaller

**Unchanged**
Asset | File Size | % Changed
----- | --------- | ---------
index.js | 3.88 MB | 0%
</div>
</details>

---

#### cli

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
1 | 7.91 MB | 0%

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
No assets were added

**Removed**
No assets were removed

**Bigger**
No assets were bigger

**Smaller**
No assets were smaller

**Unchanged**
Asset | File Size | % Changed
----- | --------- | ---------
cli.js | 7.91 MB | 0%
</div>
</details>
</details>

### CODE REVIEW

**Comment by sk10727-a11y** [comment]
@matt-fidd I'm not sure if you have capacity or if you are the right maintainer to tag, but would you be available to review this PR? Just wanted to reach out to a maintainer since it has been a few weeks!

**Comment by matt-fidd** [comment]
Thanks for the ping! I'll take a look at this.

I tried to test it but it looks like the account input has been removed, could you take a look?

image

**Comment by sk10727-a11y** [comment]
> Thanks for the ping! I'll take a look at this.
> 
> I tried to test it but it looks like the account input has been removed, could you take a look?
> 
> image

Thanks for flagging! I just updated, and it should be working now.

File: packages/desktop-client/src/components/filters/FiltersMenu.tsx [hunk 1]
```diff
@@ -138,7 +144,181 @@ function ConfigureField<T extends RuleConditionEntity>({
 
   // For ops that filter based on payeeId, those use PayeeFilter, otherwise we use GenericInput
   const isPayeeIdOp = (op: T['op']) =>
```
Comment (matt-fidd) [inline packages/desktop-client/src/components/filters/FiltersMenu.tsx]: I think `isPayeeIdOp` is a misnomer here, it may only be used in a payee context, but that's not what it actually stores

File: packages/desktop-client/src/components/filters/FiltersMenu.tsx [hunk 2]
```diff
@@ -138,7 +144,181 @@ function ConfigureField<T extends RuleConditionEntity>({
...
+      return matches.length === 1 ? matches[0].id : null;
+    }
+    return null;
+  };
+
+  const isIdField =
+    field === 'account' || field === 'payee' || field === 'category';
+
+  // Converting values when switching between ops is a bit tricky, so we have some specific rules:
+  const setOp = (nextOp: T['op']) => {
```
Comment (matt-fidd) [inline packages/desktop-client/src/components/filters/FiltersMenu.tsx:226]: It would be brilliant to add some tests for this if you feel up for it. I won't block on it, but I'd hate for this to be lost in a regression later down the line!

**Review by matt-fidd — DISMISSED** [review]
This is brilliant, thank you for your work here!

I've left a couple of comments, but it's your choice whether to implement them or not. You could always defer to another PR if you don't want to tackle them right now as well.

Let me know what you'd like to do, and I'll either merge or wait for you to resolve them

File: packages/desktop-client/src/components/filters/FiltersMenu.tsx (hunk 1 above)
Comment (sk10727-a11y) [reply packages/desktop-client/src/components/filters/FiltersMenu.tsx]: Good point! Renamed to reflect that it is for ID-based operators rather than anything payee-specific.

File: packages/desktop-client/src/components/filters/FiltersMenu.tsx (hunk 2 above)
Comment (sk10727-a11y) [reply packages/desktop-client/src/components/filters/FiltersMenu.tsx:226]: Sounds good! I'll follow up with another PR.

**Review by matt-fidd — APPROVED** [review]
Thank you!

**Comment by matt-fidd** [comment]
@coderabbitai resolve
