### PR TITLE
:electron: Prevent keyboard shortcuts modal when entering shortcut into editable field

### LINKED ISSUE #3369: [Bug]: typing a question mark (?) in a field in the macOS app triggers the keyboard shortcuts dialog
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Typing a question mark (`?`) while an input field —for example, a line item's Payee field, Notes field, Category field, etc.— has focus opens the keyboard shortcuts dialog.

### Expected

The app distinguishes between typing the character `?` and using it to trigger the keyboard shortcuts dialog: the keyboard shortcuts dialog does not open when an input field has focus.

The web UI uses the expected behavior.

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Mac OSX

### PR DESCRIPTION
**Pull request by MikesGlitch**
Should close #3369

### CODE REVIEW

File: packages/desktop-client/src/index.tsx [hunk 1]
```diff
@@ -70,16 +70,25 @@ handleGlobalEvents(boundActions, store);
...
+  return (
+    window.document.activeElement.tagName === 'INPUT' ||
+    window.document.activeElement.tagName === 'TEXTAREA' ||
+    (window.document.activeElement as HTMLElement).isContentEditable
+  );
+}
+
 // Expose this to the main process to menu items can access it
-window.__actionsForMenu = boundActions;
+window.__actionsForMenu = { ...boundActions, inputFocused };
```
Comment (MikesGlitch) [inline packages/desktop-client/src/index.tsx:91]: Adding the util to the menu actions

File: packages/desktop-electron/menu.ts [hunk 2]
```diff
@@ -179,7 +179,7 @@ export function getMenu(
           click: function (_menuItem, focusedWin) {
             if (focusedWin) {
               focusedWin.webContents.executeJavaScript(
-                'window.__actionsForMenu && window.__actionsForMenu.pushModal("keyboard-shortcuts")',
+                'window.__actionsForMenu && !window.__actionsForMenu.inputFocused() && window.__actionsForMenu.pushModal("keyboard-shortcuts")',
```
Comment (MikesGlitch) [inline packages/desktop-electron/menu.ts:182]: Showing modal when the currently active element is not an input

**Review by matt-fidd — APPROVED** [review]
LGTM
