### PR TITLE
:bug: (schedules) fix creating schedules with the same name

### LINKED ISSUE #1375: [Bug]: Deleting and creating a schedule with the same name results in an error
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Tried deleting an existing schedule and create a new one with the same name results in an error:
image

### What error did you receive?

image

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by MatissJanis**
Closes #1375

### CODE REVIEW

File: packages/loot-core/migrations/1691233396000_add_schedule_next_date_tombstone.sql [hunk 1]
```diff
@@ -0,0 +1,5 @@
+BEGIN TRANSACTION;
+
+ALTER TABLE schedules_next_date ADD COLUMN tombstone INTEGER DEFAULT 0;
```
Comment (MatissJanis) [inline packages/loot-core/migrations/1691233396000_add_schedule_next_date_tombstone.sql:3]: This fixes another (different) issue.

Reproduction:
1. create a new schedule
2. ctrl+z to undo the creation
3. before: it breaks; now: it works

**Review by shall0pass — APPROVED** [review]
