### PR TITLE
:bug: Schedule table in Link Schedule modal is collapsed

### LINKED ISSUE #1500: [Bug]: Schedule table in Link Schedule modal is collapsed
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Can be seen on demo.actualbudget.org. 

Repro steps:
0. Ensure at least one schedule exists
1. In any For Budget account, select one or more rows. 
2. On the Transaction menu, click Link Schedule
  Screenshot 2023-08-09 at 9 20 15 PM

3. Observe how the table of schedules shows no rows (they're there, just squished to height 0)
  Screenshot 2023-08-09 at 9 17 38 PM

### What error did you receive?

No errors in the devtools console.

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

_No response_

### Operating System

None

### PR DESCRIPTION
**Pull request by trevdor**
Fixes #1500 

* Converted LinkSchedule module to TS
* Enhanced (hopefully) the copy in the modal body.

### CODE REVIEW

File: packages/desktop-client/src/components/schedules/LinkSchedule.tsx [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+  transactionIds: ids,
+}: {
+  actions: BoundActions;
+  modalProps?: CommonModalProps;
+  transactionIds: string[];
+}) {
+  let [filter, setFilter] = useState('');
+
+  let scheduleData = useSchedules({
+    transform: useCallback((q: any) => q.filter({ completed: false }), []),
```
Comment (trevdor) [inline packages/desktop-client/src/components/schedules/LinkSchedule.tsx:27]: Used `any` as a last resort here. 

@albertogasparin Can you offer any insight as to a more appropriate type for `q` here, given the expected type for the `transform` function [from schedules.tsx](https://github.com/actualbudget/actual/blob/bug/1500-empty-schedules-modal/packages/loot-core/src/client/data-hooks/schedules.tsx#L21)?

Comment (kyrias) [reply packages/desktop-client/src/components/schedules/LinkSchedule.tsx:27]: I'm pretty sure that the actual fix is

```diff
diff --git a/packages/loot-core/src/client/data-hooks/schedules.tsx b/packages/loot-core/src/client/data-hooks/schedules.tsx
index 61e24192..3603561f 100644
--- a/packages/loot-core/src/client/data-hooks/schedules.tsx
+++ b/packages/loot-core/src/client/data-hooks/schedules.tsx
@@ -1,5 +1,6 @@
 import React, { createContext, useEffect, useState, useContext } from 'react';
 
+import { type Query } from '../../shared/query';
 import { getStatus, getHasTransactionsQuery } from '../../shared/schedules';
 import q, { liveQuery } from '../query-helpers';
 
@@ -18,7 +19,7 @@ function loadStatuses(schedules, onData) {
   });
 }
 
-type UseSchedulesArgs = { transform?: <T>(v: T) => T };
+type UseSchedulesArgs = { transform?: (q: Query) => Query };
 export function useSchedules({ transform }: UseSchedulesArgs = {}) {
   let [data, setData] = useState(null);
 
```

Then you can have the `useCallback` call either un-annotated or be `(q: Query)`.

Comment (trevdor) [reply packages/desktop-client/src/components/schedules/LinkSchedule.tsx:27]: I like it, @kyrias. Thanks.
Looked around and `Query` works for everywhere we use `useSchedules`.
Annnnd, the usage in EditRule.js would make TS mad just like this one did when I first converted it.

File: packages/desktop-client/src/components/Modals.tsx [hunk 2]
```diff
@@ -28,6 +29,15 @@ import ScheduleDetails from './schedules/EditSchedule';
 import ScheduleLink from './schedules/LinkSchedule';
 import PostsOfflineNotification from './schedules/PostsOfflineNotification';
 
+export type CommonModalProps = {
```
Comment (MatissJanis) [inline packages/desktop-client/src/components/Modals.tsx:32]: **👏 praise:** ‏thanks! This will be useful when porting the other modals to TS. But would you mind moving this type to `modals.types.ts` or other such file? This will help us get rid of a circular dependency once the other modals are migrated (i.e. modal X imports `CommonModalProps` from `Modals.tsx`, but `Modals.tsx` also imports modal X)

File: packages/desktop-client/src/components/schedules/LinkSchedule.tsx [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+import { useSchedules } from 'loot-core/src/client/data-hooks/schedules';
+import { send } from 'loot-core/src/platform/client/fetch';
+import { type Query } from 'loot-core/src/shared/query';
+
+import { type BoundActions } from '../../hooks/useActions';
+import Modal from '../common/Modal';
+import Search from '../common/Search';
+import Text from '../common/Text';
+import View from '../common/View';
+import { type CommonModalProps } from '../Modals';
```
Comment (MatissJanis) [inline packages/desktop-client/src/components/schedules/LinkSchedule.tsx:12]: This is the circular dependency I meant.

- `LinkSchedule` depends on `Modals`
- `Modals` depends on `LinkSchedule`

image

**Review by MatissJanis — APPROVED** [review]
Overall LGTM. Just one small nitpick

File: packages/desktop-client/src/components/Modals.tsx (hunk 2 above)
Comment (trevdor) [reply packages/desktop-client/src/components/Modals.tsx:32]: Good call, thanks for catching that.

**Comment by kyrias** [comment]
I just updated to the latest `edge` and instead of showing _no_ schedules we're now showing too many, making the entire modal go off the screen and making it impossible to select among all of the schedules I have.

**Comment by kyrias** [comment]
> Please ignore if I have completely misunderstood all this! However, I am also running the latest Edge and the attached is what I see. [CleanShot 2023-08-21@2x copy.pdf](https://github.com/actualbudget/actual/files/12399195/CleanShot.2023-08-21%402x.copy.pdf)

This is about the "Link Schedule" modal you get when you select a transaction and try to link it to a schedule.

**Comment by kyrias** [comment]
And for more context, it's _supposed_ to look like this, but it's showing all of them and so everything except for part of the list ends up off-screen.

image

**Comment by Kidglove57** [comment]
@kyrias Apologies for my misunderstanding. I dont think I have ever used that function.
One thing I did notice when looking at my existing individual scheduled transactions - the prior linked transactions used to show at the bottom but now they are not visible - here is an example:
CleanShot 2023-08-21 2@2x

**Comment by trevdor** [comment]
@kyrias That's my fault. I gave the list a reasonable flex-basis but let it grow unbounded. Fixed here: https://github.com/actualbudget/actual/pull/1563

@Kidglove57 The collapsed Linked transactions table is a problem...but unrelated in code (very related in user experience). I gave it a look while fixing the above, but didn't have time to solve it. Will have to be addressed separately.

**Comment by Kidglove57** [comment]
@trevdor 
Thank you very much for taking the time to check it out! I have a feeling the issue may be a few weeks or more old. I noticed it a while back and then forgot about it again!

**Comment by trevdor** [comment]
@Kidglove57 I'd like to get Matiss to weigh in on my approach, but I created a new PR to fix the bug you noticed: #1571

**Comment by Kidglove57** [comment]
@trevdor Thank you for working on this so quickly. I have tested this with my live file and it works for me as I would expect!
