### PR TITLE
🐛 added null/undefined check for scheduleIsRecurring

### LINKED ISSUE #4624: [Bug]: There was an unrecoverable error in the UI. Sorry!
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

When trying to open an account I get: "There was an unrecoverable error in the UI. Sorry!"

Here is the log:

```
react-dom.production.min.js:189 TypeError: Cannot read properties of null (reading 'op')
    at Fg (schedules.ts:395:39)
    at transactions.ts:182:29
    at Array.map (<anonymous>)
    at transactions.ts:176:8
    at Object.b8 [as useMemo] (react-dom.production.min.js:179:119)
    at ht.useMemo (react.production.min.js:25:208)
    at cKe (transactions.ts:159:32)
    at v (useAccountPreviewTransactions.ts:30:5)
    at Hs (Account.tsx:179:5)
```

The stack trace points to this piece of code:
```js
export function scheduleIsRecurring(dateCond) {
  const cond = new Condition(dateCond.op, 'date', dateCond.value, null);
  const value = cond.getValue();

  return value.type === 'recur';
}
```

This error only happens with one of the three bank accounts I have 

Client version: v25.3.1
Server version: v25.3.1

### How can we reproduce the issue?

How can we reproduce the issue?

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

### PR DESCRIPTION
**Pull request by alecbakholdin**
resolves #4624

### CODE REVIEW

File: packages/loot-core/src/shared/schedules.ts [hunk 1]
```diff
@@ -425,7 +425,10 @@ export function getUpcomingDays(upcomingLength = '7'): number {
   }
 }
 
-export function scheduleIsRecurring(dateCond) {
+export function scheduleIsRecurring(dateCond: Condition) {
+  if (!dateCond) {
+    return false;
+  }
```
Comment (MatissJanis) [inline packages/loot-core/src/shared/schedules.ts:431]:
```suggestion
export function scheduleIsRecurring(dateCond: Condition | null) {
  if (!dateCond) {
    return false;
  }
```

**Review by MatissJanis — APPROVED** [review]
Thanks!
