### PR TITLE
:bug: Mobile: Account ledger jumps on first selection

### LINKED ISSUE #1621: [Bug]: Mobile: Account ledger jumps on first selection
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

If I scroll down an account ledger on the mobile interface and select a transaction, the first time I try the interface will jump instead of opening the transaction.  The second attempt is  successful. The video below only shows the first attempt on the demo budget.

https://github.com/actualbudget/actual/assets/20625555/13f0fd77-ca41-40e1-93a5-495f917547c2

### What error did you receive?

_No response_

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

### PR DESCRIPTION
**Pull request by trevdor**
Fixes #1621

The first time you interact with the list, react-aria sets the focused element to the first list item, then scrolls that focused element into view. 

The offending `onFocus` listener appears fixed by upgrading `@react-aria/listbox`. I went ahead and upgraded all react-aria packages, as they get frequent updates and work with one another. 

Tested the mobile list components thoroughly and everything seems to work as normal.

### CODE REVIEW

File: packages/desktop-client/src/components/accounts/MobileAccount.js [hunk 1]
```diff
@@ -185,33 +185,8 @@ export default function Account(props) {
...
 
   const onSelectTransaction = transaction => {
-    if (isPreviewId(transaction.id)) {
-      let parts = transaction.id.split('/');
-      let scheduleId = parts[1];
-
-      let options = ['Post transaction', 'Skip scheduled date', 'Cancel'];
-      let cancelButtonIndex = 2;
-
-      props.showActionSheetWithOptions(
```
Comment (trevdor) [inline packages/desktop-client/src/components/accounts/MobileAccount.js:195]: Removed this whole block as `showActionSheetWithOptions` is never defined.

File: packages/desktop-client/src/components/transactions/MobileTransaction.js [hunk 2]
```diff
@@ -1057,7 +1057,7 @@ export class TransactionList extends Component {
         >
           {sections.length === 0 ? (
             <Section>
-              <Item>
```
Comment (trevdor) [inline packages/desktop-client/src/components/transactions/MobileTransaction.js:1060]: Fixing an accessibility warning. `<Item>`s whose children aren't plain text must have a `textValue`

**Review by MatissJanis — APPROVED** [review]
LGTM. Just missing release note file
