### PR TITLE
Fix title first null undefined

### LINKED ISSUE #4906: [Bug]: When opening specific account - There was an unrecoverable error in the UI. Sorry!
### Verified issue does not already exist?

- [x] I have searched and found no existing issue - There are similar issues that have been merged, but don't specifically call out opening an account.

### What happened?

I am attempting to open a specific account and get the following error, in both my local version and what's on the edge version: 

Local:

TypeError: Cannot read properties of undefined (reading '0') at ih 
(https://xxx/static/js/index.EbjK2svi.js:50:37887) at 
https://xxx/static/js/index.EbjK2svi.js:269:36006 at VC 
(https://xxx/static/js/index.EbjK2svi.js:47:19552) at h$ 
(https://xxx/static/js/index.EbjK2svi.js:49:3143) at i7 
(https://xxx/static/js/index.EbjK2svi.js:49:2355) at N5 
(https://xxx/static/js/index.EbjK2svi.js:49:1897) at $7 
(https://xxx/static/js/index.EbjK2svi.js:49:47385) at k7 
(https://xxx/static/js/index.EbjK2svi.js:49:39809) at qre 
(https://xxx/static/js/index.EbjK2svi.js:49:39735) at R1 
(https://xxx/static/js/index.EbjK2svi.js:49:39585)

Edge
TypeError: Cannot read properties of undefined (reading '0') at Gh (https://edge.actualbudget.org/static/js/index.QKWGxwBO.js:59:37887) at https://edge.actualbudget.org/static/js/index.QKWGxwBO.js:267:36014 at xD (https://edge.actualbudget.org/static/js/index.QKWGxwBO.js:57:34255) at WT (https://edge.actualbudget.org/static/js/index.QKWGxwBO.js:57:62173) at $z (https://edge.actualbudget.org/static/js/index.QKWGxwBO.js:57:61092) at DO (https://edge.actualbudget.org/static/js/index.QKWGxwBO.js:57:60646) at jz (https://edge.actualbudget.org/static/js/index.QKWGxwBO.js:57:75055) at Jz (https://edge.actualbudget.org/static/js/index.QKWGxwBO.js:57:106615) at Eoe (https://edge.actualbudget.org/static/js/index.QKWGxwBO.js:57:105673) at C2 (https://edge.actualbudget.org/static/js/index.QKWGxwBO.js:57:105501)

### How can we reproduce the issue?

1. Open Actual
2. Select problem account

I would like to provide a sample file but I don't know how to ensure my privacy as it has sensitive information in it, as you could expect.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 10

### PR DESCRIPTION
**Pull request by alecbakholdin**
Fixed a undefined reference issue

closes #4906

### CODE REVIEW

File: packages/loot-core/src/shared/util.ts [hunk 1]
```diff
@@ -205,6 +205,9 @@ export function fastSetMerge<T>(set1: Set<T>, set2: Set<T>) {
 }
 
 export function titleFirst(str: string) {
```
Comment (jfdoming) [inline packages/loot-core/src/shared/util.ts:207]:
```suggestion
export function titleFirst(str: string | null | undefined) {
```

**Review by jfdoming — APPROVED** [review]
