### PR TITLE
:bug:  disable 'all payees' checkbox while schedules are loading

### LINKED ISSUE #1125: [Bug]: Checking 'Payee' checkbox on find schedules crashes app
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

If you click the 'Payee' checkbox on the find schedules page **while the spinner is still going**, it crashes the app. Reproduced on my stable version as well as dev.

### What error did you receive?

image

image

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by MatissJanis**
Closes #1125

Disables (hides) the "all payees" checkbox when schedules are loading.

Reproduction:
1. open `/schedule/discover`
2. while the data is still loading - click on the checkbox in the table header
3. after loading finishes - the page crashes with an error

### CODE REVIEW

**Review by j-f1 — APPROVED** [review]

File: packages/desktop-client/src/hooks/useSendPlatformRequest.ts [hunk 1]
```diff
@@ -0,0 +1,28 @@
+import { useEffect, useState } from 'react';
+
+import { send } from 'loot-core/src/platform/client/fetch';
+import type { Handlers } from 'loot-core/src/types/handlers';
+
+export default function useSendPlatformRequest<K extends keyof Handlers>(
```
Comment (j-f1) [inline packages/desktop-client/src/hooks/useSendPlatformRequest.ts:6]: Very cool!
