### PR TITLE
fix responsiveness of mobile navigation with longer translation strings

### LINKED ISSUE #5425: [Bug]: "Settings" option missing in Bottom Bar on narrow screen devices (Logout not possible)
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

On narrow-width devices (smartphones), the "Settings" option is not visible in the bottom navigation bar of the app. This prevents users from accessing the settings menu entirely, including the option to change the GUI language or logout.

In my case, my device is using system language settings (German), and I only see the following bottom bar options:

- Budget
- Transactions
- Accounts
- Reports
- Schedules (soon)
- Payees (soon)
- Rules (soon)

The problem seems specific to narrow-width displays, as rotating the phone to landscape mode shows the full (desktop-like) interface where the settings may be accessible.

### How can we reproduce the issue?

Steps to reproduce:

- Use a smartphone or device with a narrow screen.
- Open the app with system language set to something other than English (e.g., German).
- Attempt to access "Settings" via the bottom navigation bar.
- Observe that the "Settings" option is not available.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

### PR DESCRIPTION
**Pull request by Serializator**
<p>
  
  
  
</p>

Fixes #5425

### CODE REVIEW

File: packages/desktop-client/src/components/mobile/MobileNavTabs.tsx [hunk 1]
```diff
@@ -265,12 +267,18 @@ function NavTab({ Icon: TabIcon, name, path, style, onClick }: NavTabProps) {
...
+        justifyContent: 'center',
         ...style,
       })}
       onClick={onClick}
     >
-      <TabIcon width={22} height={22} />
+      <TabIcon
+        width={22}
+        height={22}
+        style={{ margin: '0 0 5px 0', minHeight: '22px' }}
```
Comment (matt-fidd) [inline packages/desktop-client/src/components/mobile/MobileNavTabs.tsx]: Is the 5px margin required here? It's not a huge difference but I preferred the more compact look from before.

Comment (Serializator) [reply packages/desktop-client/src/components/mobile/MobileNavTabs.tsx]: It's not required, I only felt the text otherwise was too close to the icon. There is no strong opinion on my side so I'll revert it. This may also help with less VRT changes 😄

File: packages/desktop-client/src/components/mobile/MobileNavTabs.tsx [hunk 2]
```diff
@@ -265,12 +267,14 @@ function NavTab({ Icon: TabIcon, name, path, style, onClick }: NavTabProps) {
         flexDirection: 'column',
         textDecoration: 'none',
         textAlign: 'center',
+        textWrap: 'balance',
         userSelect: 'none',
+        justifyContent: 'center',
```
Comment (matt-fidd) [inline packages/desktop-client/src/components/mobile/MobileNavTabs.tsx]: Sorry, I'm really nitpicking now, but this centres the buttons within the lower div of the nav tab, which puts it lower than the true centre point when you include the grab handle.

Is it needed for spacing when the text wraps or could it be removed?

If it's needed then a negative margin of about -6 or -7px could be added here to recentre it here 
https://github.com/actualbudget/actual/pull/5429/files#diff-d13f9632e3584faa5579f2064dbf9383cc1f7bebfaedd9f98789e67cd289e6f9R229-R238

Comment (Serializator) [reply packages/desktop-client/src/components/mobile/MobileNavTabs.tsx]: A nitpick a day keeps the ~~bugs~~ **cough** features away 😄

It is not needed for anything related to the original bug report. Removed it 👍🏼

**Review by matt-fidd — APPROVED** [review]
Looking good! Thanks for being so responsive to my feedback.
