### PR TITLE
[Goals] Fix some schedule template regressions

### LINKED ISSUE #6562: [Bug]: Regression in v26.1.0: #template schedule underfunds multi-month schedules after skipped months
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

In Actual **v26.1.0**, #template schedule <SCHEDULE_NAME> can **underfund** a category for a multi-month schedule when some months are skipped/left at 0.

Observed behavior: if I skip funding for one or more months, the schedule template will “catch up” only on the first subsequent month, but then it **reverts back to the original base monthly amount** even though the category is still behind, and the **due month arrives underfunded**.

This looks like a regression. Same budget file + same actions:
- ✅ v25.12.0: behaves like the equivalent `#template <amount> by <date>` (keeps increasing all remaining months as needed)
- ❌ v26.1.0: catch-up happens once, then it reverts to base amount and the due month can be missed

### How can we reproduce the issue?

I’m attaching a minimal test budget file that defines a single schedule:
- Name: `TEST_SCHEDULE`
- Amount: 50
- Recurrence: every 6 months
- Starts: 2025-10-01 (so next occurrence in cycle is 2026-04-01)

I've set 2 categories:

SCHEDULE TEMPLATE:
#template schedule TEST_SCHEDULE

BY TEMPLATE:
#template 50 by 2025-10 repeat every 6 months

If I skip october, november and december, and begin running the templates starting in 2026-01, the two templates behave *exactly* the same in v25.12 until 2026-04: they increase the budgeted amount proportionally to 12.50 to hit the due date fully funded.

Doing the exact same actions in v26.1, the schedule template only budgets 12.5 on january and reverts back to budgeting 8.33 on february, march and april, hitting the due month underfunded with 37.49 instead of 50.

[v26-1-regression-My Finances.zip](https://github.com/user-attachments/files/24442311/v26-1-regression-My.Finances.zip)

### Where are you hosting Actual?

Desktop App (Electron)

### What browsers are you seeing the problem on?

_No response_

### Operating System

Linux

### PR DESCRIPTION
**Pull request by youngcw**
fix #6562 partially #6513

### CODE REVIEW

File: packages/loot-core/src/server/budget/schedule-template.ts [hunk 1]
```diff
@@ -303,7 +308,8 @@ export async function runSchedule(
     balance >= totalSinking + totalPayMonthOf ||
     (lastMonthGoal < totalSinking + totalPayMonthOf &&
       lastMonthGoal !== 0 &&
-      balance >= lastMonthGoal)
+      balance >= lastMonthGoal &&
+      numSubMonthly > 0)
```
Comment (youngcw) [inline packages/loot-core/src/server/budget/schedule-template.ts:313]: This part of the condition is meant for sub-monthly templates, so explicitly require there to be some of those.

File: packages/loot-core/src/server/budget/schedule-template.ts [hunk 2]
```diff
@@ -208,6 +208,7 @@ function getSinkingBaseContributionTotal(t: ScheduleTemplateTarget[]) {
       case 'yearly':
         monthlyAmount = schedule.target / schedule.target_interval / 12;
         break;
+      case undefined:
```
Comment (joel-jeremy) [inline packages/loot-core/src/server/budget/schedule-template.ts]: Maybe we can handle this in `default` case?

File: packages/loot-core/src/server/budget/schedule-template.ts [hunk 3]
```diff
@@ -275,17 +276,21 @@ export async function runSchedule(
 
   const isPayMonthOf = c =>
     c.full ||
-    (c.target_frequency === 'monthly' &&
+    ((c.target_frequency === 'monthly' || c.target_frequency === undefined) &&
```
Comment (joel-jeremy) [inline packages/loot-core/src/server/budget/schedule-template.ts]: Can we use `!` here to handle both possible `null` or `undefined`?
```suggestion
    ((c.target_frequency === 'monthly' || !c.target_frequency) &&
```

File: upcoming-release-notes/6610.md [hunk 4]
```diff
@@ -0,0 +1,6 @@
+---
+category: Bugfix
+authors: [youngcw]
+---
+
+Fix schedule template regressions to improve functionality and user experience.
```
Comment (joel-jeremy) [inline upcoming-release-notes/6610.md]:
```suggestion
Fix schedule template regressions where categories are being underbudgeted and to improve functionality and user experience.
```

**Review by jfdoming — COMMENTED** [review]
Would it be possible to add a unit test for these cases?

**Comment by youngcw** [comment]
I'll look at adding tests in another PR
