### PR TITLE
fix: Tracking budget income budget fields missing in mobile view 

### LINKED ISSUE #5125: [Bug]: Tracking budget income budget fields missing in mobile view
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

After upgrading to version 25.6.1 the "to budget" fields are missing for all incomes in the mobile view only. When I switch to desktop layout I can see and use them as normal

Image

### How can we reproduce the issue?

Opening a Budget file in the browser on an android device

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

### PR DESCRIPTION
**Pull request by MatissJanis**
Fixes #5125

### CODE REVIEW

**Comment by jfdoming** [comment]
Hmm, this is causing the additional column to show up for the envelope budget as well:
image

Vs edge:
image

**Review by jfdoming — CHANGES_REQUESTED** [review]
See above (also wonder if we should have VRT for this?)

**Comment by MatissJanis** [comment]
Good spot @jfdoming . Turns out there was an even simpler fix here.. should be good now

File: packages/desktop-client/src/components/mobile/budget/BalanceCell.tsx [hunk 1]
```diff
@@ -48,22 +48,22 @@ export function BalanceCell({
   });
 
   const goal =
-    budgetType === 'report'
+    budgetType === 'tracking'
       ? trackingBudget.catGoal(category.id)
       : envelopeBudget.catGoal(category.id);
```
Comment (youngcw) [inline packages/desktop-client/src/components/mobile/budget/BalanceCell.tsx:53]: Are these ternaries even necessary?  They must have been returning the right thing even though the logic was backwards

Comment (MatissJanis) [reply packages/desktop-client/src/components/mobile/budget/BalanceCell.tsx:53]: TBH: I'm not sure.

But I do know the usage of the tracking budget is quite low. This bug was introduced [just a month ago](https://github.com/actualbudget/actual/pull/4879), so I'm guessing this issue just hasn't been noticed up till now. No reason not to fix it though.

Comment (youngcw) [reply packages/desktop-client/src/components/mobile/budget/BalanceCell.tsx:53]: Iirc, goal data is stored per category, so it should be the same on both budgets. But I don't think there is a existing way to have budget agnostic values so it's fine.
