### PR TITLE
Fix when pressing Enter adds an extra split transaction when no split remains

### LINKED ISSUE #2041: [Bug]: Pressing Enter when adding the final split transaction entry adds another child transaction
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Steps to reproduce:
1. Update an existing transaction to become a split transaction
2. Add a child transaction with a partial amount
3. Add another child transaction that with the remaining amount
4. Press Enter

Result: Another child transaction is created although there is no remaining amount left to be split

### What error did you receive?

_No response_

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by jasonmichalski**
Fixes #2041 

A race condition existed where the parent transaction in `transactionMap` was not yet updated to reflect the recently added child transaction when `onCheckEnter()` is called.

This PR gets the parent transaction from the same transactions array that the child transaction is retrieved from, which reflects the latest split calculation / error state.

### CODE REVIEW

**Review by youngcw — APPROVED** [review]

File: packages/desktop-client/src/components/transactions/TransactionsTable.jsx [hunk 1]
```diff
@@ -1967,7 +1967,10 @@ export const TransactionTable = forwardRef((props, ref) => {
       afterSave(() => {
         const transactions = latestState.current.transactions;
         const idx = transactions.findIndex(t => t.id === id);
-        const parent = transactionMap.get(transactions[idx]?.parent_id);
+        const parentIdx = transactions.findIndex(
+          t => t.id === transactions[idx]?.parent_id,
+        );
+        const parent = transactions[parentIdx];
```
Comment (kymckay) [inline packages/desktop-client/src/components/transactions/TransactionsTable.jsx:1973]: nit: you could just use `.find` directly if the index isn't used anywhere else.

Comment (jasonmichalski) [reply packages/desktop-client/src/components/transactions/TransactionsTable.jsx]: good call - fixed!

**Review by youngcw — APPROVED** [review]
