### PR TITLE
:bug: fix account filters being overridden

### LINKED ISSUE #3440: [Bug]: Filters are overwriting each other
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

In edge you can't add more than one filter at a time.  If you add one filter, then make a second one and add that, it replaces the first filter.

Replicate:
1. Open a test file in edge
2. View an account and make a filter such as category:food 
3. Make another filter such as date is >=09/01/2024
4. See that the original category filter gets replaced

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

_No response_

### Operating System

None

### PR DESCRIPTION
**Pull request by MatissJanis**
Closes #3440

### CODE REVIEW

File: packages/desktop-client/src/components/accounts/Account.tsx [hunk 1]
```diff
@@ -1357,6 +1358,18 @@ class AccountInternal extends PureComponent<
 
   onApplyFilter = async (conditionOrSavedFilter: ConditionEntity) => {
     let filterConditions = this.state.filterConditions;
+
+    if (
```
Comment (MatissJanis) [inline packages/desktop-client/src/components/accounts/Account.tsx:1362]: TBH I'm not entirely certain why we need this logic. But I have now brought it back to verbatim match what we had before (except for a few TS patches): https://github.com/actualbudget/actual/commit/5cfa2cf577d94a99ddc55b519847fd79547e881b#diff-99c276500045bfda8f9c14b3c10705730a1fe7452a69246d4e40d092c24d305eL1199

**Review by MikesGlitch — APPROVED** [review]
Works for me
