### PR TITLE
Fix/5840 escape search wildcards

### LINKED ISSUE #5840: [Bug]: Transaction view - quick search with "?" finds everything
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

I have several transactions, in *one* of them I use the question mark in note field.
If I now filter in quick search with "?"

Outcome:
*All* transactions get displayed.

Expected outcome: 
Just show transactions with a question mark in note field.

It seems, the question mark is a "query wildcard" character and is not escaped correctly.

### How can we reproduce the issue?

see above.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by eduardopio03**
## Description

When a user types special characters such as ? or % into the transaction quick search bar, all transactions were returned instead of only those matching the literal character. This happened because these characters were being passed unescaped into $like query patterns, where they acted as regex wildcards inside the custom UNICODE_LIKE function.

The fix has two parts:
- In transactionsSearch (index.ts), the search string is now escaped before being used in $like patterns, so ? and % are prefixed with \ to signal they should be treated as literals.
- In unicodeLike.ts, the pattern-to-regex converter is updated to recognise these escape sequences and convert them to properly escaped regex literals instead of wildcards. This directly addresses the TODO comment already present in that file.

## Related issue(s)

Fixes #5840

## Testing

1. Create a transaction with ? or % in the notes or payee name field.
2. Open the transaction view and type ? or % in the quick search bar.
3. Before fix: all transactions are shown.
4. After fix: only transactions containing the literal ? or % are shown.
5. Verify that normal searches (e.g. plain text, amounts, dates) still work correctly.

## Checklist

- [x] Release notes added (see link above)
- [x] No obvious regressions in affected areas
- [x] Self-review has been performed - I understand what each change in the code does and why it is needed

<hr />

### Bundle Stats

Bundle | Files count | Total bundle size | % Changed
------ | ----------- | ----------------- | ---------
desktop-client | 27 | 12.41 MB → 12.41 MB (+93 B) | +0.00%
loot-core | 1 | 4.84 MB → 4.84 MB (+466 B) | +0.01%
api | 1 | 3.83 MB → 3.84 MB (+446 B) | +0.01%
cli | 1 | 7.89 MB | 0%

<details>
<summary>View detailed bundle stats</summary>

#### desktop-client

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
27 | 12.41 MB → 12.41 MB (+93 B) | +0.00%

<details>
<summary>Changeset</summary>

File | Δ | Size
---- | - | ----
`src/queries/index.ts` | 📈 +93 B (+4.26%) | 2.13 kB → 2.22 kB
</details>

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
No assets were added

**Removed**
No assets were removed

**Bigger**
Asset | File Size | % Changed
----- | --------- | ---------
static/js/useTransactionBatchActions.js | 4.33 MB → 4.33 MB (+93 B) | +0.00%

**Smaller**
No assets were smaller

**Unchanged**
Asset | File Size | % Changed
----- | --------- | ---------
static/js/index.js | 3.31 MB | 0%
static/js/BackgroundImage.js | 121.09 kB | 0%
static/js/FormulaEditor.js | 852.77 kB | 0%
static/js/ReportRouter.js | 1.17 MB | 0%
static/js/TransactionList.js | 82.49 kB | 0%
static/js/ca.js | 189.75 kB | 0%
static/js/da.js | 104.66 kB | 0%
static/js/de.js | 174.38 kB | 0%
static/js/en-GB.js | 8.2 kB | 0%
static/js/en.js | 175.65 kB | 0%
static/js/es.js | 181.8 kB | 0%
static/js/fr.js | 177.08 kB | 0%
static/js/indexeddb-main-thread-worker-e59fee74.js | 13.46 kB | 0%
static/js/it.js | 165.87 kB | 0%
static/js/narrow.js | 363.02 kB | 0%
static/js/nb-NO.js | 151.85 kB | 0%
static/js/nl.js | 108.93 kB | 0%
static/js/pl.js | 88.34 kB | 0%
static/js/pt-BR.js | 177.44 kB | 0%
static/js/resize-observer.js | 18.06 kB | 0%
static/js/th.js | 179.3 kB | 0%
static/js/theme.js | 30.79 kB | 0%
static/js/uk.js | 212.6 kB | 0%
static/js/wide.js | 295 B | 0%
static/js/workbox-window.prod.es5.js | 7.33 kB | 0%
static/js/zh-Hans.js | 94.19 kB | 0%
</div>
</details>

---

#### loot-core

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
1 | 4.84 MB → 4.84 MB (+466 B) | +0.01%

<details>
<summary>Changeset</summary>

File | Δ | Size
---- | - | ----
`home/runner/work/actual/actual/packages/loot-core/src/platform/server/sqlite/unicodeLike.ts` | 📈 +466 B (+84.88%) | 549 B → 1015 B
</details>

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
Asset | File Size | % Changed
----- | --------- | ---------
kcab.worker.BNveTyqm.js | 0 B → 4.84 MB (+4.84 MB) | -

**Removed**
Asset | File Size | % Changed
----- | --------- | ---------
kcab.worker.B7SvglID.js | 4.84 MB → 0 B (-4.84 MB) | -100%

**Bigger**
No assets were bigger

**Smaller**
No assets were smaller

**Unchanged**
No assets were unchanged
</div>
</details>

---

#### api

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
1 | 3.83 MB → 3.84 MB (+446 B) | +0.01%

<details>
<summary>Changeset</summary>

File | Δ | Size
---- | - | ----
`home/runner/work/actual/actual/packages/loot-core/src/platform/server/sqlite/unicodeLike.ts` | 📈 +446 B (+81.54%) | 547 B → 993 B
</details>

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
No assets were added

**Removed**
No assets were removed

**Bigger**
Asset | File Size | % Changed
----- | --------- | ---------
index.js | 3.83 MB → 3.84 MB (+446 B) | +0.01%

**Smaller**
No assets were smaller

**Unchanged**
No assets were unchanged
</div>
</details>

---

#### cli

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
1 | 7.89 MB | 0%

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
No assets were added

**Removed**
No assets were removed

**Bigger**
No assets were bigger

**Smaller**
No assets were smaller

**Unchanged**
Asset | File Size | % Changed
----- | --------- | ---------
cli.js | 7.89 MB | 0%
</div>
</details>
</details>

### CODE REVIEW

File: packages/loot-core/src/platform/server/sqlite/unicodeLike.ts [hunk 1]
```diff
@@ -2,28 +2,42 @@ import { LRUCache } from 'lru-cache';
...
+  while (i < pattern.length) {
+    const ch = pattern[i];
+    if (ch === '\\' && i + 1 < pattern.length) {
+      const next = pattern[i + 1];
+      if (next === '%' || next === '?') {
+        // escaped wildcard — treat as literal character
+        regexStr += next.replace(/[.*+^${}()|[\]\\?]/g, '\\$&'); // ? added here
+        i += 2;
+        continue;
+      }
```
[the remark this answers is not in the document]
Comment (matt-fidd) [reply packages/loot-core/src/platform/server/sqlite/unicodeLike.ts:19]: I think the rabbit is correct here @eduardopio03, the escape regex is `/[\\%_?]/g` which escapes `_`. But in `likePatternToRegex`, the escape handler only recognizes \% and \? so searching for `_` would actually search for `\_`.

We don't use `_` as a wildcard so dropping it from the escape regex in `queries/index` would make sense.

File: packages/loot-core/src/platform/server/sqlite/unicodeLike.ts [hunk 2]
```diff
@@ -2,28 +2,42 @@ import { LRUCache } from 'lru-cache';
...
 const likePatternCache = new LRUCache<string, RegExp>({ max: 500 });
 
+function likePatternToRegex(pattern: string): RegExp {
+  let regexStr = '';
+  let i = 0;
+  while (i < pattern.length) {
+    const ch = pattern[i];
+    if (ch === '\\' && i + 1 < pattern.length) {
+      const next = pattern[i + 1];
+      if (next === '%' || next === '?') {
```
Comment (matt-fidd) [inline packages/loot-core/src/platform/server/sqlite/unicodeLike.ts]: I think we need to add an escapement for `\` too, otherwise we wouldn't be able to search for backslashes, if I'm understanding this correctly.

```suggestion
      if (next === '%' || next === '?' || next === '\\') {
```

Comment (eduardopio03) [reply packages/loot-core/src/platform/server/sqlite/unicodeLike.ts]: You right, yeah

**Comment by eduardopio03** [comment]
@matt-fidd Already did you requests :) Hope everything it's right

**Comment by matt-fidd** [comment]
> @matt-fidd Already did you requests :) Hope everything it's right

Thank you!

Looks like there's just one comment left, and that's to remove the handling in the `escapedSearch` regex, because it shouldn't be treated as a wildcard.

**Comment by eduardopio03** [comment]
> > @matt-fidd Already did you requests :) Hope everything it's right
> 
> Thank you!
> 
> Looks like there's just one comment left, and that's to remove the handling in the `escapedSearch` regex, because it shouldn't be treated as a wildcard.

Removed `_` from the `escapedSearch` regex in `index.ts`! Everything should be good to go.

**Comment by StephenBrown2** [comment]
Wait, I considered this a feature, not a bug. How often do payees actually contain special characters?

**Comment by eduardopio03** [comment]
> Wait, I considered this a feature, not a bug. How often do payees actually contain special characters?

I guess, in the "notes" you can put wathever you want.

**Comment by StephenBrown2** [comment]
This is true, but even more of a reason to include wildcard characters. In that case, can you make it escape only for the notes field? https://github.com/actualbudget/actual/pull/7270/changes#diff-d8fa4e0507344fcd8454e77d6dec4adb052acaea5abb19682dc861998cb2f4c5R103

**Comment by eduardopio03** [comment]
> This is true, but even more of a reason to include wildcard characters. In that case, can you make it escape only for the notes field? https://github.com/actualbudget/actual/pull/7270/changes#diff-d8fa4e0507344fcd8454e77d6dec4adb052acaea5abb19682dc861998cb2f4c5R103

@StephenBrown2 I understand the value of having wildcards for advanced searches! However, the quick search uses an $or condition across all fields. If we leave the notes field unescaped, typing a ? in the search bar will still return all transactions (because the unescaped notes field will match everything). This would defeat the purpose of fixing the bug reported in #5840.

@matt-fidd since you reviewed the initial fix, what is your take on this? I'm happy to adjust the code, but I want to make sure we don't accidentally reintroduce the bug for the global search. Let me know how you'd like to proceed!

**Comment by eduardopio03** [comment]
Hi @matt-fidd! I would love to see this closed. Can you take a look?

**Comment by matt-fidd** [comment]
> Hi @matt-fidd! I would love to see this closed. Can you take a look?

Hey, thanks for your work on this. I understand Stephen's points here, and also what you've said about the or operator making it return everything regardless. I've been tossing this one about in my head, and i think that most users will expect it to be escaped and won't be using the wildcards, so we can go ahead with this.

The search is pretty rudimentary at the moment, some sort of fuzzy search algorithm would be great down the road.

File: packages/loot-core/src/platform/server/sqlite/unicodeLike.ts [hunk 3]
```diff
@@ -2,28 +2,42 @@ import { LRUCache } from 'lru-cache';
...
+function likePatternToRegex(pattern: string): RegExp {
+  let regexStr = '';
+  let i = 0;
+  while (i < pattern.length) {
+    const ch = pattern[i];
+    if (ch === '\\' && i + 1 < pattern.length) {
+      const next = pattern[i + 1];
+      if (next === '%' || next === '?' || next === '\\') {
+        // escaped wildcard — treat as literal character
+        regexStr += next.replace(/[.*+^${}()|[\]\\?]/g, '\\$&'); // ? added here
```
Comment (matt-fidd) [inline packages/loot-core/src/platform/server/sqlite/unicodeLike.ts]: Is this and line 24 meant to be the same regex? Can you extract it out to a variable and reuse it so that it stays consistent?

something like 

`const REGEX_SPECIAL = /[.*+^${}()|[\]\\?]/g;` you can use in both places.

**Review by matt-fidd — CHANGES_REQUESTED** [review]

File: packages/loot-core/src/platform/server/sqlite/unicodeLike.ts (hunk 3 above)
Comment (eduardopio03) [reply packages/loot-core/src/platform/server/sqlite/unicodeLike.ts]: Done!
