### PR TITLE
:bug:  fix sync: add back 'accounts.type' column

### LINKED ISSUE #1296: [Bug]: Sync error after upgrade to v23.7.1
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Upgraded to v23.7.1 and now I'm getting this error when I'm syncing:
image

### What error did you receive?

_No response_

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by MatissJanis**
Closes #1296

After this is merged I'll do an API release which will also solve https://github.com/actualbudget/actual/issues/1303

### CODE REVIEW

**Comment by j-f1** [comment]
How do you feel about doing #1318 instead? Tested it out with the workflow you mentioned in the issue and it seems to correctly drop the message.

File: packages/loot-core/migrations/1688841238000_add_account_type.sql [hunk 1]
```diff
@@ -0,0 +1,5 @@
+BEGIN TRANSACTION;
+
+ALTER TABLE accounts ADD COLUMN type INTEGER;
```
Comment (j-f1) [inline packages/loot-core/migrations/1688841238000_add_account_type.sql:3]: Wasn’t it a string before? This might still break sync since the message includes the account type as part of its value.

**Review by j-f1 — APPROVED** [review]

**Comment by MatissJanis** [comment]
Ok, I'll go for this solution for now just because it seems to be the easier one in the short term. But we can definitely circle back to your solution when I get back from holidays.
