### PR TITLE
[Mobile] Fix #3214 - Pull down to refresh triggering clicks on budget cells

### LINKED ISSUE #3214: [Bug]: Pull to refresh on mobile does not prevent tap on budget row
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

How to reproduce:
1. Go to https://demo.actualbudget.org on a mobile device
2. View demo file
3. Pull down to refresh

Pulling down to refresh should prevent the tap from registering on the budget row/category header that was pulled down on. Instead, when you lift up your finger after pulling down, the budget category opens as if you tapped on it. This  behavior seems to have been newly introduced in the last release.

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Firefox

### Operating System

Mobile Device

### PR DESCRIPTION
**Pull request by joel-jeremy**
Resolves #3214 

The `CellValue` component has been refactored to be more composable. To fix the cell value components in the mobile budget table, I had to update them to use the new react aria Button - this looks to have fixed the issue.

Not sure what are causing some of VRT screenshots to change but it looks like the color changed on them.

### CODE REVIEW

File: packages/desktop-client/src/hooks/usePreviewTransactions.ts [hunk 1]
```diff
@@ -53,7 +53,7 @@ export function usePreviewTransactions(
           })),
         }));
         setPreviewTransactions(ungroupTransactions(withDefaults));
-        collapseTransactions(withDefaults.map(t => t.id));
+        collapseTransactions?.(withDefaults.map(t => t.id));
```
Comment (joel-jeremy) [inline packages/desktop-client/src/hooks/usePreviewTransactions.ts:56]: This is resulting in an error in console.log. Fixing it here.

File: packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-1-chromium-linux.png
Comment (youngcw) [inline packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-1-chromium-linux.png:1]: The sign on the budgeted value in the table disappeared

File: packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-1-chromium-linux.png
Comment (youngcw) [inline packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-1-chromium-linux.png:1]: The budgeted value shifted slightly but thats not a huge deal I would think.

Comment (joel-jeremy) [reply packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-loads-the-budget-page-with-budgeted-amounts-1-chromium-linux.png:1]: Should be fixed now :)

File: packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-1-chromium-linux.png
Comment (joel-jeremy) [reply packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-1-chromium-linux.png:1]: Should be fixed now :)

Comment (youngcw) [inline packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-1-chromium-linux.png:1]: Still seeing the same thing.  I guess it would be more accurate to say that the budgeted total gained a sign where it should be a positive listing where the header now shows negative.

Comment (joel-jeremy) [reply packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-1-chromium-linux.png:1]: Weird. It's fixed when you access the link but it still shows in the VRT screenshot. There seem to be something weird with the VRT tests it's not detecting the changes made I had to delete the screenshots and rerun the VRT.

File: packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-1-chromium-linux.png
Comment (matt-fidd) [inline packages/desktop-client/e2e/mobile.test.js-snapshots/Mobile-opens-individual-account-page-and-checks-that-filtering-is-working-1-chromium-linux.png:1]: This one doesn't look quite right

**Comment by tim-smart** [comment]
Not sure if intentional, but this changes the colour of zero values on the mobile budget table.

**Comment by joel-jeremy** [comment]
Fixed the VRT. I had to checkout the entire e2e/ folder from master and rerun the VRT again.

**Comment by joel-jeremy** [comment]
> Not sure if intentional, but this changes the colour of zero values on the mobile budget table.

I think the zero values in edge is broken. All zeroes used to grayed out before, similar to how it is in desktop.

**Comment by tim-smart** [comment]
> I think the zero values in edge is broken. All zeroes used to be grayed out before, similar to how it is in desktop.

Ah right. I think we might need to bump the contrast on the gray in another PR, it is quite hard to see the text - even if it is demoted in importance.

**Review by matt-fidd — APPROVED** [review]
Certainly fixes the issue functionally, and I can't see any glaring issues with the refactor.
You might want someone with a little more TS/React prowess to review the finer details before merge though.

**Comment by joel-jeremy** [comment]
@MatissJanis Would you mind reviewing on top of @matt-fidd's approval?

**Comment by MatissJanis** [comment]
👋 I'm not sure I follow the refactored logic here. Am I missing something?

The issue appeared when we moved from the old `Button` to `Button2`. So surely we'll have the same issue in other parts of the app too that use drag-to-refresh functionality, no? Such as: account list, single account page.

This makes me think that the patch should be in `Button2` and not specifically isolated to the budget component tree. 

But again: probably I'm missing something.

**Comment by joel-jeremy** [comment]
> 👋 I'm not sure I follow the refactored logic here. Am I missing something?
> 
> The issue appeared when we moved from the old `Button` to `Button2`. So surely we'll have the same issue in other parts of the app too that use drag-to-refresh functionality, no? Such as: account list, single account page.
> 
> This makes me think that the patch should be in `Button2` and not specifically isolated to the budget component tree.
> 
> But again: probably I'm missing something.

The issue happens because the CellValue wraps the Button2 components (budget cell and balance cell) with a Text component. The click handler is attached to the Text component instead of the underlying Button2 component which causes the quirky behavior we see here. So the refactor is to allow us to render the cell value as Button2 (without being wrapped by a Text component) and allows us to attach the click handler on the button which handles it in a more standard way.

It doesn't happen in the other parts of the app because the Button2 in those parts are not wrapped with another component.

**Review by MatissJanis — APPROVED** [review]
