### PR TITLE
:bug:  fix number formatter not listening to state changes

### LINKED ISSUE #1415: [Bug]: updating formatting in settings doesn't update sidebar
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Regression: If you update number formatting in settings, the sidebar doesn't update anymore, without refreshing the page. The transactions in account do use new formatting immediately.

A git bisect pointed to ba2de7ece5ae048beb55f96d40bce19a9fd8b718. There, I saw use of `useMemo` in `<CellValue/>`. From what I understand, `useMemo` has to take the number format and related settings as a dependency, which I do not know how to fix.

| Working before ba2de7ece5ae048beb55f96d40bce19a9fd8b718 | Not working in master |
| --- | --- |
| <video src="https://github.com/actualbudget/actual/assets/8426945/77e680d5-e359-46d4-9ea7-a36e92d5fb88"/> | <video src="https://github.com/actualbudget/actual/assets/8426945/afadf1dd-edc7-489e-8a47-f24d37250b4b"/> |

### What error did you receive?

_No response_

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

### PR DESCRIPTION
**Pull request by MatissJanis**
Closes #1415

Fix number formatter not listening to state changes. This is not a fully comprehensive solution. We will need to run a migration campaign to port over from direct usage of `format` util to `useFormat`, but this is a first step that solves the most glaring issue.

### CODE REVIEW

**Comment by MatissJanis** [comment]
The plan is to open up a migration ticket for the work that needs to be done after this is merged.

File: packages/desktop-client/src/components/spreadsheet/format.ts [hunk 1]
```diff
@@ -31,8 +41,23 @@ export default function format(value, type = 'string'): string {
...
   }
 }
+
+export function useFormat() {
+  const numberFormat = useSelector(state =>
+    getNumberFormat({
+      format: state.prefs.local.numberFormat,
+      hideFraction: state.prefs.local.hideFraction,
+    }),
+  );
```
Comment (j-f1) [inline packages/desktop-client/src/components/spreadsheet/format.ts:56]: Since `getNumberFormat` returns an object literal, this will return a different value on every render and cause excessive rerendering. I would recommend fetching each of the state values separately, then using `useMemo` to construct the number format.

**Review by j-f1 — CHANGES_REQUESTED** [review]

File: packages/desktop-client/src/components/spreadsheet/format.ts (hunk 1 above)
Comment (MatissJanis) [reply packages/desktop-client/src/components/spreadsheet/format.ts]: Good shout. Added `reselect` that will take care of this. We should port all other selectors to it too.

**Review by j-f1 — APPROVED** [review]
