### PR TITLE
[FIX] Update DesktopLinkedNotes so links stay inline

### LINKED ISSUE #6842: [Bug]: wrapping occurring on notes that should fit on a single line.
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

Image

### How can we reproduce the issue?

Add a note like this:

line 1 [🔗](line2)

You will see the link appears on line 2

This only happened with the latest update (26.2.0)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by Juulz**
Use link.tsx instead of button or text or span. Fixes #6842 

Before
Screenshot 2026-02-04 100123

After
Screenshot 2026-02-04 154539

<hr />

### Bundle Stats

Bundle | Files count | Total bundle size | % Changed
------ | ----------- | ----------------- | ---------
desktop-client | 27 | 14.48 MB → 14.48 MB (+222 B) | +0.00%
loot-core | 1 | 5.86 MB | 0%
api | 1 | 4.39 MB | 0%

<details>
<summary>View detailed bundle stats</summary>

#### desktop-client

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
27 | 14.48 MB → 14.48 MB (+222 B) | +0.00%

<details>
<summary>Changeset</summary>

File | Δ | Size
---- | - | ----
`src/notes/DesktopLinkedNotes.tsx` | 📈 +222 B (+13.16%) | 1.65 kB → 1.86 kB
</details>

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
No assets were added

**Removed**
No assets were removed

**Bigger**
Asset | File Size | % Changed
----- | --------- | ---------
static/js/index.js | 9.33 MB → 9.33 MB (+222 B) | +0.00%

**Smaller**
No assets were smaller

**Unchanged**
Asset | File Size | % Changed
----- | --------- | ---------
static/js/indexeddb-main-thread-worker-e59fee74.js | 12.94 kB | 0%
static/js/workbox-window.prod.es5.js | 5.64 kB | 0%
static/js/da.js | 106.62 kB | 0%
static/js/de.js | 178.39 kB | 0%
static/js/en-GB.js | 7.18 kB | 0%
static/js/en.js | 164.55 kB | 0%
static/js/es.js | 173.83 kB | 0%
static/js/fr.js | 179.62 kB | 0%
static/js/it.js | 171.44 kB | 0%
static/js/nb-NO.js | 157.23 kB | 0%
static/js/nl.js | 106.65 kB | 0%
static/js/pl.js | 88.64 kB | 0%
static/js/pt-BR.js | 154.57 kB | 0%
static/js/sv.js | 78.2 kB | 0%
static/js/th.js | 182.35 kB | 0%
static/js/uk.js | 215.11 kB | 0%
static/js/resize-observer.js | 18.37 kB | 0%
static/js/BackgroundImage.js | 120.54 kB | 0%
static/js/ReportRouter.js | 1.12 MB | 0%
static/js/narrow.js | 640.46 kB | 0%
static/js/TransactionList.js | 105.97 kB | 0%
static/js/wide.js | 160.07 kB | 0%
static/js/AppliedFilters.js | 9.71 kB | 0%
static/js/usePayeeRuleCounts.js | 11.79 kB | 0%
static/js/useTransactionBatchActions.js | 13.23 kB | 0%
static/js/FormulaEditor.js | 1.04 MB | 0%
</div>
</details>

---

#### loot-core

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
1 | 5.86 MB | 0%

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
No assets were added

**Removed**
No assets were removed

**Bigger**
No assets were bigger

**Smaller**
No assets were smaller

**Unchanged**
Asset | File Size | % Changed
----- | --------- | ---------
kcab.worker.BmGAOUic.js | 5.86 MB | 0%
</div>
</details>

---

#### api

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
1 | 4.39 MB | 0%

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
No assets were added

**Removed**
No assets were removed

**Bigger**
No assets were bigger

**Smaller**
No assets were smaller

**Unchanged**
Asset | File Size | % Changed
----- | --------- | ---------
bundle.api.js | 4.39 MB | 0%
</div>
</details>
</details>

### CODE REVIEW

**Comment by Juulz** [comment]
I prolly should have used AI (but I can't as I don't have access to enough bandwidth to be useful). It took me quite a bit of time tracking this little bug down.

**Comment by youngcw** [comment]
Long urls are getting completely cut off.  Is there maybe something we could do to make them only partially cut down?
image

**Comment by Juulz** [comment]
Looking at the console elements and the code, the notes field gets broken into "segments". For plain text, each word is a segment, for tags and links, the whole thing is a segment. If you make a tag long enough, it will not be shown at all, either. 

Here I made one and then tried to click the blank area and got the tag:

Screenshot 2026-02-04 122128

**Comment by Juulz** [comment]
I really don't know enough about how the overflow CSS styling works, perhaps if we added text-overlow: clip (the default) to remove the ellipsis?

**Comment by Juulz** [comment]
Hmmm... I looked at the deploy from Dec 6th and they weren't getting cut off. Let me try to see if I can get it back. This was introduced with the table updates.

**Comment by Juulz** [comment]
This was introduced in #6679 with a button change, not in the table update.  Comments made during the 6679 update led me to remove the button link and use a text link so this would not break again.

File: packages/desktop-client/src/notes/DesktopLinkedNotes.tsx [hunk 1]
```diff
@@ -59,9 +62,9 @@ export function DesktopLinkedNotes({
 
   return (
     <>
-      <Button variant="bare" style={linkStyles} onPress={handleClick}>
+      <Text className={linkStyles} onClick={handleClick}>
         {displayText}
-      </Button>
+      </Text>
```
[the remark this answers is not in the document]
Comment (Juulz) [reply packages/desktop-client/src/notes/DesktopLinkedNotes.tsx]: Tabbing into this field selects the entire field. Pressing Enter activates a hotkey to enter the field and move down to the next transaction. AFAICT changing from a "button" to text did not change the functionality of the field.

**Review by matt-fidd — APPROVED** [review]
Seems to work, I don't mind this being `Text` but I'll cc @MatissJanis to give any opinions about https://github.com/actualbudget/actual/pull/6679

File: packages/desktop-client/src/notes/DesktopLinkedNotes.tsx [hunk 2]
```diff
@@ -59,9 +62,9 @@ export function DesktopLinkedNotes({
 
   return (
     <>
-      <Button variant="bare" style={linkStyles} onPress={handleClick}>
+      <Text className={linkStyles} onClick={handleClick}>
```
Comment (joel-jeremy) [inline packages/desktop-client/src/notes/DesktopLinkedNotes.tsx]: I think using Text (which is a span) here would prevent screen readers from knowing that the element is clickable. Would <a> element work here?

Comment (Juulz) [reply packages/desktop-client/src/notes/DesktopLinkedNotes.tsx]: I have no idea - I'm just learning this ts and css stuff on the fly! Feel free to do whatever! or tell me where to find the info.

Comment (Juulz) [reply packages/desktop-client/src/notes/DesktopLinkedNotes.tsx]: OH - I just copied the mobile version but added the hover.

It was a button and that button worked, but #6679 broke it when it was changed to bare button. We could revert it to the original code.

Comment (Juulz) [reply packages/desktop-client/src/notes/DesktopLinkedNotes.tsx]: It looks like role="link" will fix screen readers but not sure where to put that. I'll do a little reading and get that put in there first thing tomorrow if this is still sitting here.

**Comment by Juulz** [comment]
NVM the following, it works correctly now.

~~The original did not have `role="button"` for accessibility. The `role="button"` was added in #6560  for accessibility.  
The links are just a `<span>`, not a real button. When the role is added, the code fails lint and ci with warnings, but works really well. In this particular case, we don't want key handlers and we don't prefer button over role, so the code fails lint. 
I tried many many various ways of formatting the field and/or the link and when they worked in one respect, they broke something else. I think the original with the added role is the best way to handle this, regardless of lint.~~

**Comment by Juulz** [comment]
Alrighty! 😅 This actually works correctly now. From what I can tell, this is the correct way to do this. 

@youngcw you'll be glad to know that you can squish the long links correctly.

**Comment by raf-vale** [comment]
What do you think if we allow the input field to expand for longer notes? It would make easier to read and write longer notes

**Comment by Juulz** [comment]
> What do you think if we allow the input field to expand for longer notes? It would make easier to read and write longer notes

I think that would be a good idea, but it would mean a change on transactiontable.tsx and should be on a different PR, I think.  If you want to do it, it's formatted about line 1400.

**Comment by youngcw** [comment]
> What do you think if we allow the input field to expand for longer notes? It would make easier to read and write longer notes

The transaction table is in the midst or a total rewrite.  Resizeble columns can come after that

**Comment by youngcw** [comment]
Seems to work well.  Ill let @joel-jeremy decide if its a good fix or not.
