### PR TITLE
Fix: update toolbar server status on sync

### LINKED ISSUE #3128: [Bug]: says "server offline" when it actually came back
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I started Actual while my wifi was on but disconnected.  It tried to sync, and failed.  The top-right said "server offline":

image

I then connected to my wiif.  I hit the 'sync' button.  It seemed to connect and sync, and further hitting 'sync' almost instantly returned.  Yet this is what I see:

image

What I expected was it would update to this (which is what I see if I close and restart the app):

image

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

### PR DESCRIPTION
**Pull request by p-payet**
Fixes #3128 

Listen to `sync-event` to update user data when sync status changed, so `userData.offline` is up to date and server status displayed is valid.

### CODE REVIEW

File: packages/desktop-client/src/components/LoggedInUser.tsx [hunk 1]
```diff
@@ -52,14 +53,41 @@ export function LoggedInUser({
   const currentFile = remoteFiles.find(f => f.cloudFileId === cloudFileId);
   const hasSyncedPrefs = useSelector((state: State) => state.prefs.synced);
 
-  useEffect(() => {
-    async function init() {
+  const initializeUserData = async () => {
```
Comment (joel-jeremy) [inline packages/desktop-client/src/components/LoggedInUser.tsx:56]: This should be defined inside the useEffect hook

Comment (p-payet) [reply packages/desktop-client/src/components/LoggedInUser.tsx:56]: There is now 2 different `useEffect`. The first one is calling `initializeUserData` after first rendering, and the second one is used to listen to `sync-event` and call `initializeUserData` when needed, and is dependant to `userData`.

Both are using the `initializeUserData` method, it is for this reason that `initializeUserData` is defined outside the `useEffect` hooks.

Can you explain in more detail how `initializeUserData` definition should be done?

**Review by joel-jeremy — APPROVED** [review]
