### PR TITLE
Disable fontSizeChanged to prevent undo stack exceeding limit after dashboard reset

### LINKED ISSUE #6074: [Bug]: reports - undo broken when using "reset to default"
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

"reset to default" + "ctrl+z" combination is not working.

### How can we reproduce the issue?

1. open reports page
2. change the report
3. click "reset to default report"
4. tap "ctrl+z"
5. nothing happens (expectation: old report is visible)

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

_No response_

### Operating System

None

### PR DESCRIPTION
**Pull request by pyfisssh**
Fixes #6074 

#### Summary
Undo functionality was broken after using "reset to default" due to the `fontSizeChanged` function in SummaryNumber.tsx.

The reset uses `DEFAULT_DASHBOARD_STATE` (loot-core/src/shared/dashboard.ts), which contains widget fontSize values that differ from those calculated on the frontend. After a reset, `fontSizeChanged` always triggers `dashboard-update-widget`, modifying the undo stack and preventing users from undoing back to the pre-reset state.

Additionally, `fontSizeChanged` can cause an infinite loop. Based on testing, this PR temporarily disables `fontSizeChanged` during dashboard reset. I believe addressing `fontSizeChanged` itself to be a separate issue, but I am not sure if the maintainers would agree.

#### Screen Recording

Issue demonstration — `fontSizeChanged` behavior:

Screenshot 2025-11-09 at 10 45 26 PM

---

> [!NOTE]
> Removes the `fontSizeChanged` callback from `SummaryNumber` in `SummaryCard.tsx` and adds a bugfix release note.
> 
> - **Reports**:
>   - In `packages/desktop-client/src/components/reports/reports/SummaryCard.tsx`, remove `fontSizeChanged` callback when rendering `SummaryNumber` (still passes `initialFontSize`).
> - **Release Notes**:
>   - Add bugfix entry `upcoming-release-notes/6094.md` describing the `fontSizeChanged` disablement.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit fdf1baa1d4659bf52d9bd12d8c019069f2a323c2. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: packages/desktop-client/src/components/reports/reports/SummaryCard.tsx [hunk 1]
```diff
@@ -151,13 +151,13 @@ export function SummaryCard({
               suffix={content.type === 'percentage' ? '%' : ''}
               loading={!data}
               initialFontSize={content.fontSize}
-              fontSizeChanged={newSize => {
```
Comment (qunm00) [inline packages/desktop-client/src/components/reports/reports/SummaryCard.tsx:154]: Good find!

I think you only need to keep this change. The other changes can be kept.

This change removes onMetaChange call when fontSizeChanged is called. onMetaChange subsequently calls 'dashboard-update-widget' then an infinite loop is created.

Also, once you are satisfied with your PR, you can remove [WIP] label to let maintainers know that the PR is ready for review. Something I learned.

Comment (pyfisssh) [reply packages/desktop-client/src/components/reports/reports/SummaryCard.tsx:154]: Thanks. I've updated the code as suggested.
