### PR TITLE
:bug: (popover) fix date popover closing when editing a filter

### LINKED ISSUE #3005: [Bug]: Datepicker in filter menu will not allow changing the date after applied
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

As above, video below for reproduction instructions. Reproducible on edge.actualbudget.org

https://github.com/actualbudget/actual/assets/81489167/54adb678-860d-4349-acbf-5f8bb5cd8f52

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by MatissJanis**
Closes #3005

### CODE REVIEW

File: packages/desktop-client/src/components/filters/FilterExpression.tsx [hunk 1]
```diff
@@ -100,6 +102,21 @@ export function FilterExpression({
         placement="bottom start"
         isOpen={editing}
         onOpenChange={() => setEditing(false)}
+        shouldCloseOnInteractOutside={element => {
```
Comment (MatissJanis) [inline packages/desktop-client/src/components/filters/FilterExpression.tsx:105]: Same patch as here: https://github.com/actualbudget/actual/blob/0ee91268205ffca5f857dc51bace85c5a91689c9/packages/desktop-client/src/components/filters/FiltersMenu.jsx#L372-L386

**Review by youngcw — APPROVED** [review]
