### PR TITLE
Fix net worth graph gradient conflict

### LINKED ISSUE #3965: [Bug]: Having 2 net worth widgets with 1 being positive and 1 being negative removes any red colour from either widget.
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When you have 2 net worth widgets where 1 has a filter and is fully positive it will cause the red color of debt to disappear.
image

Compared to:
image

And:

image

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by OlivierKamers**
Fixes #3965

Ensures that the net worth graph's gradient ID is unique to prevent conflicts when multiple graphs are rendered on the same page.

To verify, I added a Net Worth Chart to the reports page of the test budget, where I simply added a filter `amount < 1000` to make the net worth negative.

**Before**

Screenshot 2025-06-08 at 15 53 53

**After**

Screenshot 2025-06-08 at 15 54 00

### CODE REVIEW

File: packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx [hunk 1]
```diff
@@ -74,6 +75,7 @@ export function NetWorthGraph({
   };
 
   const off = gradientOffset();
+  const gradientId = `splitColor-${id}`;
```
Comment (OlivierKamers) [inline packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx:78]: An alternative would be to use `splitColor-${off}` since the conflict is fine then. To me using an id feels cleaner/safer to avoid further conflicts if different styling is applied to the gradient depending on other params.

**Review by matt-fidd — APPROVED** [review]
Great, thank you. I agree that the ID sounds better than using the gradient
