### PR TITLE
:bug: (import) patch phantom transactions getting created

### LINKED ISSUE #2432: [Bug]: Phantom transactions added when imported CSV with same date/amount
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### Is this related to GoCardless, Simplefin or another bank-sync provider?

- [ ] I have checked my server logs and could not see any errors there
- [ ] I will be attaching my server logs to this issue
- [ ] I will be attaching my client-side (browser) logs to this issue
- [ ] I understand that this issue will be automatically closed if insufficient information is provided

### What happened?

Reproduce steps:
1. Create a new account
2. Import the followingCSV file [acutalbug.csv](https://github.com/actualbudget/actual/files/14520662/acutalbug.csv)
```csv
Date,Payee,Amount
02/11/2024,A,-1
02/08/2024,A,-1
02/02/2024,A,-1
```
4. Observed that 3 transactions have been imported 
5. Imported the CSV again, a phantom 4th transaction will be created
image

I haven't verified yet, but I think this is a regression for the newest version, since I import the same csv file without problems for a long time

### What error did you receive?

Phantom transactions added after import

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by MatissJanis**
Closes #2432

### CODE REVIEW

File: packages/loot-core/src/server/accounts/sync.ts [hunk 1]
```diff
@@ -645,6 +655,16 @@ export async function reconcileTransactions(acctId, transactions) {
...
+
+      // Sort the matched transactions according to the distance from the original
+      // transactions date. i.e. if the original transaction is in 21-02-2024 and
+      // the matched transactions are: 20-02-2024, 21-02-2024, 29-02-2024 then
+      // the resulting data-set should be: 21-02-2024, 20-02-2024, 29-02-2024.
+      fuzzyDataset = fuzzyDataset.sort((a, b) => {
+        const aDistance = Math.abs(db.toDateRepr(trans.date) - a.date);
+        const bDistance = Math.abs(db.toDateRepr(trans.date) - b.date);
+        return aDistance > bDistance ? 1 : -1;
+      });
```
Comment (MatissJanis) [inline packages/loot-core/src/server/accounts/sync.ts:667]: It would be nice to unify `reconcileExternalTransactions` and `reconcileTransactions`. But that's a story for another day.

**Review by youngcw — APPROVED** [review]
