### PR TITLE
Fix/saved filters position

### LINKED ISSUE #6535: [Bug]: saved filters - wrong position in the dropdown
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

The "saved" filters option should be the very last one in the list. And there should be a separating line between this option and the others to better highlight that these are not simple filters, but something "special".

Image

### How can we reproduce the issue?

Open the filters menu on account page

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

_No response_

### Operating System

None

### PR DESCRIPTION
**Pull request by FictionFics**
## Summary
Fixes #6535

This PR moves the "saved filters" option to the end of the filters dropdown menu and adds a separator to distinguish it from regular filter options.

## Changes
- Reorganized filter menu items to place 'saved filters' at the end
- Added separator before 'saved filters' to distinguish from regular filters
- Maintained alphabetical sorting for regular filter options

## Implementation Details
The solution uses a custom sort function in the Menu component that:
1. Places 'saved' field at the end of the list
2. Keeps regular filters alphabetically sorted
3. Adds a separator item between regular and saved filters

## Testing
- [x] Local testing: Unable to test due to environment setup issues
- [x] Will test on Netlify preview deployment once available
- [x] Expected behavior:
  - "Saved filters" appears at the end of dropdown
  - Visual separator before "Saved filters"
  - Other filters remain alphabetically sorted
  - All filter functionality works correctly

## Screenshots
Screenshot 2026-01-05 at 09 36 41

## Summary by CodeRabbit

* **Bug Fixes**
  * Moved saved filters to the end of the filter dropdown and added a non-interactive divider to separate them.
  * Preserved alphabetical sorting within each group so items remain ordered.
  * Saved filters remain selectable after the divider.

* **Documentation**
  * Added a release-note entry documenting this bug fix.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/desktop-client/src/components/filters/FiltersMenu.tsx [hunk 1]
```diff
@@ -477,13 +477,26 @@ export function FilterButton<T extends RuleConditionEntity>({
...
+              .filter(f => f[0] !== 'saved')
+              .sort()
+              .map(([name, text]) => ({
+                name,
+                text: titleFirst(text),
+              })),
+
+            Menu.line,
+
+            ...translatedFilterFields
```
Comment (MatissJanis) [inline packages/desktop-client/src/components/filters/FiltersMenu.tsx]: **🔨 warning:** ‏that's quite a lot of duplication. Could you instead extract the `saved` filter from the list [here](https://github.com/FictionFics/actual/blob/7ef35a16d5dd64cb685ef1e10bf12e9afafdb0cf/packages/desktop-client/src/components/filters/FiltersMenu.tsx#L72) and inline it at the end manually?

**Review by MatissJanis — CHANGES_REQUESTED** [review]
Also: please remove the "[WIP]" PR title prefix once this is ready for a final code review.
