### PR TITLE
fix #2363 broken create schedule from transaction

### LINKED ISSUE #2363: [Bug]: Creating Schedule from transaction doesn't work
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### Is this related to GoCardless, Simplefin or another bank-sync provider?

- [ ] I have checked my server logs and could not see any errors there
- [ ] I will be attaching my server logs to this issue
- [ ] I will be attaching my client-side (browser) logs to this issue
- [ ] I understand that this issue will be automatically closed if insufficient information is provided

### What happened?

When attempting to create a schedule from a transaction nothing happens.  The console shows an error after clicking the "Create new" button.

### What error did you receive?

The console output is always something along these lines
```
ScheduleDetails.jsx:227 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at w (ScheduleDetails.jsx:227:67)
    at ScheduleDetails.jsx:253:5
    at Pg (react-dom.production.min.js:244:332)
    at Ol (react-dom.production.min.js:286:111)
    at QL (react-dom.production.min.js:283:409)
    at Fa (react-dom.production.min.js:281:398)
    at Yk (react-dom.production.min.js:273:439)
    at Ia (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
```

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

_No response_

### Operating System

None

### PR DESCRIPTION
**Pull request by youngcw**
Attempt to fix #2363 bug causing the create schedule from transaction feature to not work.  I dont understand why this broke when the pr build works fine.

### CODE REVIEW

File: packages/desktop-client/src/components/schedules/ScheduleDetails.jsx [hunk 1]
```diff
@@ -225,7 +225,9 @@ export function ScheduleDetails({ modalProps, actions, id, transaction }) {
               _account: transaction.account,
               _amount: transaction.amount,
               _amountOp: 'is',
-              name: transaction.payee ? payees[transaction.payee].name : '',
+              name: transaction.payee
+                ? payees[payees.findIndex(e => e.id === transaction.payee)].name
```
Comment (youngcw) [inline packages/desktop-client/src/components/schedules/ScheduleDetails.jsx:229]: `payees` is an array of objects so searching for the index then using that index to get the name fixed the bug I was seeing.  I don't understand JS enough to have an idea why it worked before.

**Review by twk3 — CHANGES_REQUESTED** [review]
Instead of using index, let's fix the payees variable. It looks like it was broken when the hooks were updated.

Around line 74:

Change `const payees = usePayees({ idKey: true });`

To be `const payees = getPayeesById(usePayees());`

And add the import 

```
import { getPayeesById } from 'loot-core/src/client/reducers/queries';
```

I believe that should fix it.

**Review by twk3 — APPROVED** [review]
