### PR TITLE
Fix form submission on TransferTooltip when pressing enter

### LINKED ISSUE #284: Moving money between categories
When I click on a category's Balance column and select "Transfer to another category", the dialog pops up saying "Transfer this amount:".  It allows you to enter an amount (defaulting to the category's balance, if any) and then you select the category you want to transfer to/from.  But I can't hit enter to select "Transfer" have to use the mouse to hit the button.  I think it would be more convenient to keep hands on the keyboard throughout this exercise.

### PR DESCRIPTION
**Pull request by gsumpster**
Resolves #284! It looks like this behavior was intended previously but didn't work because the Input component catches the Enter key and calls onEnter instead.

CleanShot 2023-02-04 at 11 25 10

### CODE REVIEW

File: packages/loot-design/src/components/budget/rollover/TransferTooltip.js [hunk 1]
```diff
@@ -83,11 +83,7 @@ export default function TransferTooltip({
         onUpdate={id => {}}
         onSelect={id => setCategory(id)}
         inputProps={{
-          onKeyDown: e => {
-            if (e.keyCode === 13) {
-              submit();
-            }
-          }
+          onEnter: () => submit()
         }}
```
Comment (j-f1) [inline packages/loot-design/src/components/budget/rollover/TransferTooltip.js:87]: Small nit: can you condense this down to a one-liner?

```suggestion
        inputProps={{ onEnter: submit }}
```

Comment (gsumpster) [reply packages/loot-design/src/components/budget/rollover/TransferTooltip.js]: Done!

**Review by j-f1 — APPROVED** [review]
Awesome, LGTM!
