### PR TITLE
Fix crash when undoing a rule application

### LINKED ISSUE #1831: [Bug]: Undo after applying a rule gives error
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Create a new rule, apply it for at least a transaction, save the rule. Undo it by pressing CTRL + Z and you get a Fatal error message.

### What error did you receive?

_No response_

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by jfdoming**
Fix crash when hitting undo after applying a rule to some transactions (closes #1831).

Question: This fix exposes some weird (pre-existing) behaviour, where hitting undo for a rule-apply causes the application to send you to the rules page with no modal open, which is confusing as you do not see the transactions you are undoing the change for. We could:
1. Send the user to the rules page AND open the "Edit rule" modal again, showing the previously-applied transactions.
2. Send the user to the transactions page with the previously-edited transactions selected.
IMHO 1 makes more sense and would be easier to implement, but I'm curious which you think is better! A similar issue also exists on the Payees page.

### CODE REVIEW

**Comment by joel-jeremy** [comment]
@jfdoming Thank you for creating a fix! I can verify that this fixes the issue but I can't seem to replicate the behavior mentioned in your question. Could you create an issue for it and provide some steps to reproduce? We can merge this PR and handle the other issue on a separate one.

File: packages/desktop-client/src/components/Modals.tsx [hunk 1]
```diff
@@ -137,7 +137,7 @@ export default function Modals() {
           return (
             <ManageRulesModal
               modalProps={modalProps}
-              payeeId={options.payeeId}
+              payeeId={options?.payeeId}
```
Comment (MatissJanis) [inline packages/desktop-client/src/components/Modals.tsx:140]: **❓ question:** ‏is this change necessary? Doesn't the change in `ManageRules.tsx` already solve the problem?

Comment (jfdoming) [reply packages/desktop-client/src/components/Modals.tsx:140]: It's not strictly necessary, but `modals.d.ts` in `loot-core` lists `payeeId` as optional, so I thought it would make sense to match here!

**Comment by jfdoming** [comment]
> @jfdoming Thank you for creating a fix! I can verify that this fixes the issue but I can't seem to replicate the behavior mentioned in your question. Could you create an issue for it and provide some steps to reproduce? We can merge this PR and handle the other issue on a separate one.

Sounds good! I added one here: https://github.com/actualbudget/actual/issues/1945

File: packages/desktop-client/src/components/Modals.tsx (hunk 1 above)
Comment (MatissJanis) [reply packages/desktop-client/src/components/Modals.tsx:142]: That makes sense. Thanks for explaining!

**Review by MatissJanis — APPROVED** [review]

**Review by joel-jeremy — APPROVED** [review]
