### PR TITLE
Pull shiftKey state directly from the initiating event

### LINKED ISSUE #1021: [Bug]: select transactions only selects a range, and if filter is applied, selecting outside of filter crashes the app
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I was trying to select a few transactions, and noticed the select behavior is strange: it won't select anything which is not a range. If you try to select 1 then 2 then 5 it'll also select 3 and 4.

Worse, if you did a select when a filter is applied, then remove the filter and try to select something, you'll crash the app.

I can privately share a video replicating the issue, considering sensitive information shown.

### What error did you receive?

_No response_

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Linux

### PR DESCRIPTION
**Pull request by j-f1**
fixes #1021

### CODE REVIEW

File: packages/desktop-client/src/hooks/useSelected.js [hunk 1]
```diff
@@ -224,17 +223,24 @@ export function SelectedProvider({ instance, fetchAllIds, children }) {
 
   let dispatch = useCallback(
     async action => {
+      if (!action.event && isNonProductionEnvironment()) {
+        throw new Error('SelectedDispatch actions must have an event');
+      }
```
Comment (trevdor) [inline packages/desktop-client/src/hooks/useSelected.js:228]: 👏🏻 nice touch

**Review by trevdor — APPROVED** [review]
Seems like a solid approach, and works as expected in my brief testing.
