### PR TITLE
Fix/6885 crash when rule has empty date field

### LINKED ISSUE #6885: [Bug]: Crash when rule has empty date field
### What happened?

I was creating a rule to set a date and the app popped up a Fatal Error window.
Expected: App keeps running.
Actual: A Fatal Error window popped up with the message "There was an unrecoverable error in the UI. Sorry!"
Error message:
```
TypeError: Cannot read properties of null (reading 'interval') at dW
(app://actual/static/js/index.BVy2uTna.js:198:489719) at jPe
(app://actual/static/js/index.BVy2uTna.js:262:90563) at bR
(app://actual/static/js/index.BVy2uTna.js:9:49000) at BR
(app://actual/static/js/index.BVy2uTna.js:9:71973) at VG
(app://actual/static/js/index.BVy2uTna.js:9:82506) at wq
(app://actual/static/js/index.BVy2uTna.js:9:118611) at k_e
(app://actual/static/js/index.BVy2uTna.js:9:117637) at s6
(app://actual/static/js/index.BVy2uTna.js:9:117463) at pq
(app://actual/static/js/index.BVy2uTna.js:9:114205) at Iq
(app://actual/static/js/index.BVy2uTna.js:9:126346)
```

### How can we reproduce the issue?

1. Go to Rules
2. Click "Create new rule"
3. Dont enter anything, but change the "category" to "date" in section "Then apply these actions:" next to "set".
4. Click the date entry field to make it the focused field.
5. Dont enter a date.
6. Now click anywhere else, to make the date entry field lose focus.
7. Boom.

Note, if one enters a date in step 5, the problem does not happen. So it appears to be the empty date that causes is issue.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Linux

### PR DESCRIPTION
**Pull request by rznn7**
Hi, this fixes #6885.

The bug was hidden behind a `// @ts-strict-ignore` in `DateSelect.tsx`.

The root cause was `onSelect(null)` and `setSelectedValue(null)` being called on blur when the date field was empty, which crashed downstream code expecting a string. The fix replaces these with empty strings.

Also took the opportunity to remove `// @ts-strict-ignore` from the file and add correct typing.

Note: We might also want to consider replacing https://github.com/Pikaday/Pikaday as the repo has been archived since Aug 2025.

<hr />

### Bundle Stats

Bundle | Files count | Total bundle size | % Changed
------ | ----------- | ----------------- | ---------
desktop-client | 27 | 14.48 MB → 14.64 MB (+153.96 kB) | +1.04%
loot-core | 1 | 5.86 MB | 0%
api | 1 | 4.39 MB | 0%

<details>
<summary>View detailed bundle stats</summary>

#### desktop-client

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
27 | 14.48 MB → 14.64 MB (+153.96 kB) | +1.04%

<details>
<summary>Changeset</summary>

File | Δ | Size
---- | - | ----
`node_modules/moment/dist/moment.js` | 🆕 +152.78 kB | 0 B → 152.78 kB
`node_modules/moment/dist/moment.js?commonjs-proxy` | 🆕 +62 B | 0 B → 62 B
`�commonjsHelpers.js` | 📈 +739 B (+221.26%) | 334 B → 1.05 kB
`home/runner/work/actual/actual/packages/loot-core/src/shared/locale.ts` | 📈 +16 B (+3.90%) | 410 B → 426 B
`home/runner/work/actual/actual/packages/component-library/src/tokens.ts` | 📈 +2 B (+1.03%) | 195 B → 197 B
`node_modules/@ungap/structured-clone/esm/types.js` | 📈 +2 B (+0.81%) | 248 B → 250 B
`node_modules/date-fns/isValid.js` | 📈 +6 B (+0.69%) | 873 B → 879 B
`node_modules/date-fns/isAfter.js` | 📈 +4 B (+0.68%) | 590 B → 594 B
`node_modules/date-fns/isBefore.js` | 📈 +4 B (+0.67%) | 599 B → 603 B
`src/hooks/useLocale.ts` | 📈 +2 B (+0.60%) | 332 B → 334 B
`node_modules/date-fns/differenceInMilliseconds.js` | 📈 +4 B (+0.55%) | 722 B → 726 B
`home/runner/work/actual/actual/packages/loot-core/src/server/rules/rule-utils.ts` | 📈 +6 B (+0.47%) | 1.24 kB → 1.25 kB
`node_modules/date-fns/getDay.js` | 📈 +2 B (+0.37%) | 544 B → 546 B
`node_modules/date-fns/compareAsc.js` | 📈 +4 B (+0.37%) | 1.06 kB → 1.07 kB
`node_modules/date-fns/isLastDayOfMonth.js` | 📈 +2 B (+0.33%) | 605 B → 607 B
`node_modules/@ungap/structured-clone/esm/serialize.js` | 📈 +14 B (+0.32%) | 4.21 kB → 4.23 kB
`node_modules/date-fns/isWeekend.js` | 📈 +2 B (+0.31%) | 639 B → 641 B
`node_modules/date-fns/getDayOfYear.js` | 📈 +2 B (+0.31%) | 655 B → 657 B
`node_modules/date-fns/getISODay.js` | 📈 +2 B (+0.28%) | 713 B → 715 B
`src/components/select/DateSelect.tsx` | 📈 +47 B (+0.28%) | 16.69 kB → 16.74 kB
`node_modules/date-fns/isDate.js` | 📈 +2 B (+0.24%) | 838 B → 840 B
`node_modules/date-fns/locale/uk/_lib/formatRelative.js` | 📈 +4 B (+0.23%) | 1.74 kB → 1.74 kB
`node_modules/date-fns/setWeek.js` | 📈 +4 B (+0.22%) | 1.74 kB → 1.74 kB
`node_modules/date-fns/locale/be/_lib/formatRelative.js` | 📈 +4 B (+0.22%) | 1.76 kB → 1.76 kB
`node_modules/date-fns/locale/be-tarask/_lib/formatRelative.js` | 📈 +4 B (+0.22%) | 1.76 kB → 1.77 kB
`node_modules/date-fns/getISOWeek.js` | 📈 +2 B (+0.21%) | 932 B → 934 B
`node_modules/date-fns/_lib/getTimezoneOffsetInMilliseconds.js` | 📈 +2 B (+0.21%) | 944 B → 946 B
`node_modules/date-fns/locale/bg/_lib/formatRelative.js` | 📈 +4 B (+0.21%) | 1.85 kB → 1.85 kB
`node_modules/date-fns/startOfDay.js` | 📈 +2 B (+0.20%) | 1008 B → 1010 B
`node_modules/date-fns/endOfDay.js` | 📈 +2 B (+0.20%) | 1012 B → 1014 B
`node_modules/stylis/src/Tokenizer.js` | 📈 +8 B (+0.20%) | 4 kB → 4 kB
`node_modules/react-i18next/dist/es/utils.js` | 📈 +4 B (+0.19%) | 2.03 kB → 2.04 kB
`node_modules/date-fns/startOfMonth.js` | 📈 +2 B (+0.19%) | 1.04 kB → 1.04 kB
`node_modules/date-fns/startOfYear.js` | 📈 +2 B (+0.19%) | 1.04 kB → 1.04 kB
`node_modules/date-fns/setISOWeek.js` | 📈 +2 B (+0.18%) | 1.07 kB → 1.08 kB
`node_modules/date-fns/endOfMonth.js` | 📈 +2 B (+0.18%) | 1.09 kB → 1.1 kB
`node_modules/chevrotain/lib_esm/src/parse/parser/traits/context_assist.js` | 📈 +2 B (+0.17%) | 1.16 kB → 1.16 kB
`home/runner/work/actual/actual/packages/component-library/src/styles.ts` | 📈 +6 B (+0.17%) | 3.53 kB → 3.53 kB
`node_modules/date-fns/setISODay.js` | 📈 +2 B (+0.17%) | 1.18 kB → 1.19 kB
`node_modules/chevrotain/lib_esm/src/scan/tokens_public.js` | 📈 +4 B (+0.16%) | 2.38 kB → 2.38 kB
`node_modules/date-fns/addDays.js` | 📈 +2 B (+0.16%) | 1.19 kB → 1.19 kB
`node_modules/chevrotain/lib_esm/src/lang/lang_extensions.js` | 📈 +2 B (+0.15%) | 1.33 kB → 1.33 kB
`node_modules/date-fns/getISOWeekYear.js` | 📈 +2 B (+0.14%) | 1.37 kB → 1.38 kB
`node_modules/chevrotain/lib_esm/src/parse/cst/cst_visitor.js` | 📈 +8 B (+0.14%) | 5.6 kB → 5.61 kB
`node_modules/date-fns/getWeek.js` | 📈 +2 B (+0.13%) | 1.52 kB → 1.52 kB
`node_modules/chevrotain/lib_esm/src/utils/utils.js` | 📈 +14 B (+0.13%) | 10.77 kB → 10.79 kB
`node_modules/date-fns/startOfWeek.js` | 📈 +2 B (+0.12%) | 1.59 kB → 1.59 kB
`node_modules/date-fns/endOfWeek.js` | 📈 +2 B (+0.12%) | 1.59 kB → 1.59 kB
`node_modules/date-fns/toDate.js` | 📈 +2 B (+0.12%) | 1.6 kB → 1.6 kB
`node_modules/date-fns/setDay.js` | 📈 +2 B (+0.11%) | 1.71 kB → 1.71 kB
`src/components/settings/Themes.tsx` | 📈 +4 B (+0.11%) | 3.44 kB → 3.44 kB
`node_modules/chevrotain/lib_esm/src/scan/lexer.js` | 📈 +36 B (+0.10%) | 35.17 kB → 35.2 kB
`src/components/transactions/table/utils.ts` | 📈 +2 B (+0.10%) | 1.99 kB → 1.99 kB
`node_modules/@ungap/structured-clone/esm/deserialize.js` | 📈 +2 B (+0.10%) | 2 kB → 2.01 kB
`home/runner/work/actual/actual/packages/loot-core/src/server/rules/condition.ts` | 📈 +8 B (+0.09%) | 8.94 kB → 8.95 kB
`node_modules/date-fns/getWeekYear.js` | 📈 +2 B (+0.09%) | 2.28 kB → 2.29 kB
`src/queries/index.ts` | 📈 +2 B (+0.07%) | 2.61 kB → 2.61 kB
`src/components/settings/Format.tsx` | 📈 +4 B (+0.07%) | 5.68 kB → 5.68 kB
`node_modules/date-fns/addMonths.js` | 📈 +2 B (+0.07%) | 2.87 kB → 2.87 kB
`node_modules/hyperformula/es/interpreter/plugin/ComplexPlugin.mjs` | 📈 +6 B (+0.06%) | 9.16 kB → 9.17 kB
`node_modules/chevrotain/lib_esm/src/parse/parser/traits/gast_recorder.js` | 📈 +8 B (+0.06%) | 13.43 kB → 13.44 kB
`src/components/filters/FiltersMenu.tsx` | 📈 +10 B (+0.06%) | 17.48 kB → 17.49 kB
`node_modules/react-markdown/lib/index.js` | 📈 +4 B (+0.06%) | 7.05 kB → 7.05 kB
`src/components/settings/UI.tsx` | 📈 +2 B (+0.05%) | 3.65 kB → 3.65 kB
`node_modules/date-fns/parseISO.js` | 📈 +4 B (+0.05%) | 7.67 kB → 7.67 kB
`node_modules/chevrotain/lib_esm/src/scan/tokens.js` | 📈 +2 B (+0.05%) | 4.03 kB → 4.03 kB
`home/runner/work/actual/actual/packages/loot-core/src/shared/months.ts` | 📈 +4 B (+0.05%) | 8.13 kB → 8.14 kB
`node_modules/chevrotain/lib_esm/src/parse/cst/cst.js` | 📈 +4 B (+0.05%) | 8.25 kB → 8.26 kB
`src/components/modals/ImportTransactionsModal/utils.ts` | 📈 +2 B (+0.04%) | 4.78 kB → 4.79 kB
`node_modules/react-i18next/dist/es/TransWithoutContext.js` | 📈 +6 B (+0.04%) | 15.48 kB → 15.48 kB
`node_modules/chevrotain/lib_esm/src/parse/grammar/gast/gast.js` | 📈 +2 B (+0.03%) | 5.71 kB → 5.71 kB
`node_modules/chevrotain/lib_esm/src/parse/parser/traits/tree_builder.js` | 📈 +4 B (+0.03%) | 12.46 kB → 12.46 kB
`node_modules/@emotion/cache/dist/emotion-cache.browser.esm.js` | 📈 +4 B (+0.03%) | 12.93 kB → 12.93 kB
`src/components/common/Modal.tsx` | 📈 +4 B (+0.03%) | 12.94 kB → 12.94 kB
`node_modules/chevrotain/lib_esm/src/parse/parser/traits/recognizer_engine.js` | 📈 +8 B (+0.03%) | 29.49 kB → 29.5 kB
`src/components/manager/ManagementApp.tsx` | 📈 +2 B (+0.03%) | 7.46 kB → 7.46 kB
`src/components/transactions/SimpleTransactionsTable.tsx` | 📈 +2 B (+0.02%) | 9.13 kB → 9.13 kB
`src/hooks/useScheduleEdit.ts` | 📈 +2 B (+0.02%) | 10.55 kB → 10.55 kB
`node_modules/i18next/dist/esm/i18next.js` | 📈 +14 B (+0.02%) | 78.32 kB → 78.33 kB
`node_modules/chevrotain/lib_esm/src/scan/reg_exp.js` | 📈 +2 B (+0.02%) | 11.18 kB → 11.19 kB
`src/components/settings/index.tsx` | 📈 +2 B (+0.02%) | 11.45 kB → 11.45 kB
`node_modules/date-fns/format.js` | 📈 +4 B (+0.02%) | 23.75 kB → 23.75 kB
`node_modules/date-fns/parse.js` | 📈 +4 B (+0.01%) | 27.42 kB → 27.43 kB
`src/components/manager/BudgetFileSelection.tsx` | 📈 +4 B (+0.01%) | 28.48 kB → 28.48 kB
`node_modules/chevrotain/lib_esm/src/scan/lexer_public.js` | 📈 +4 B (+0.01%) | 34.08 kB → 34.09 kB
`src/components/mobile/transactions/TransactionEdit.tsx` | 📈 +4 B (+0.01%) | 61.09 kB → 61.1 kB
`node_modules/@rschedule/core/es2015/generators.js` | 📈 +4 B (+0.01%) | 65.67 kB → 65.68 kB
`node_modules/pikaday/pikaday.js` | 📉 -7 B (-0.02%) | 43.47 kB → 43.46 kB
</details>

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
No assets were added

**Removed**
No assets were removed

**Bigger**
Asset | File Size | % Changed
----- | --------- | ---------
static/js/index.js | 9.33 MB → 9.48 MB (+153.96 kB) | +1.61%

**Smaller**
No assets were smaller

**Unchanged**
Asset | File Size | % Changed
----- | --------- | ---------
static/js/indexeddb-main-thread-worker-e59fee74.js | 12.94 kB | 0%
static/js/workbox-window.prod.es5.js | 5.64 kB | 0%
static/js/da.js | 106.62 kB | 0%
static/js/de.js | 178.39 kB | 0%
static/js/en-GB.js | 7.18 kB | 0%
static/js/en.js | 164.55 kB | 0%
static/js/es.js | 173.83 kB | 0%
static/js/fr.js | 179.62 kB | 0%
static/js/it.js | 171.44 kB | 0%
static/js/nb-NO.js | 157.23 kB | 0%
static/js/nl.js | 106.65 kB | 0%
static/js/pl.js | 88.64 kB | 0%
static/js/pt-BR.js | 154.57 kB | 0%
static/js/sv.js | 78.2 kB | 0%
static/js/th.js | 182.35 kB | 0%
static/js/uk.js | 215.11 kB | 0%
static/js/resize-observer.js | 18.37 kB | 0%
static/js/BackgroundImage.js | 120.54 kB | 0%
static/js/ReportRouter.js | 1.12 MB | 0%
static/js/narrow.js | 640.46 kB | 0%
static/js/TransactionList.js | 105.97 kB | 0%
static/js/wide.js | 160.07 kB | 0%
static/js/AppliedFilters.js | 9.71 kB | 0%
static/js/usePayeeRuleCounts.js | 11.79 kB | 0%
static/js/useTransactionBatchActions.js | 13.23 kB | 0%
static/js/FormulaEditor.js | 1.04 MB | 0%
</div>
</details>

---

#### loot-core

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
1 | 5.86 MB | 0%

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
No assets were added

**Removed**
No assets were removed

**Bigger**
No assets were bigger

**Smaller**
No assets were smaller

**Unchanged**
Asset | File Size | % Changed
----- | --------- | ---------
kcab.worker.BmGAOUic.js | 5.86 MB | 0%
</div>
</details>

---

#### api

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
1 | 4.39 MB | 0%

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
No assets were added

**Removed**
No assets were removed

**Bigger**
No assets were bigger

**Smaller**
No assets were smaller

**Unchanged**
Asset | File Size | % Changed
----- | --------- | ---------
bundle.api.js | 4.39 MB | 0%
</div>
</details>
</details>

### CODE REVIEW

File: packages/desktop-client/src/components/select/DateSelect.tsx [hunk 1]
```diff
@@ -130,8 +131,8 @@ type DatePickerProps = {
   value: string;
   firstDayOfWeekIdx: string;
   dateFormat: string;
-  onUpdate?: (selectedDate: Date) => void;
```
Comment (rznn7) [inline packages/desktop-client/src/components/select/DateSelect.tsx:125]: Always passed by call sites

File: packages/desktop-client/src/components/select/DateSelect.tsx [hunk 2]
```diff
@@ -202,16 +206,16 @@ const DatePicker = forwardRef<DatePickerForwardedRef, DatePickerProps>(
...
+      mountPoint.current?.appendChild(picker.current.el);
 
       return () => {
-        picker.current.destroy();
+        picker.current?.destroy();
       };
     }, []);
 
     useEffect(() => {
-      if (value && picker.current.getDate() !== value) {
```
Comment (rznn7) [inline packages/desktop-client/src/components/select/DateSelect.tsx:205]: `picker.current.getDate() !== value` was always true because the types 'Date | null' and 'string' have no overlap.

**Comment by rznn7** [comment]
sorry, I missclicked "Close PR" :disappointed_relieved:

**Comment by joel-jeremy** [comment]
@rznn7 There are some merge conflicts that needs to be resolved

**Comment by rznn7** [comment]
@joel-jeremy should be ok :+1:

**Review by joel-jeremy — APPROVED** [review]
