### PR TITLE
fix: creating new payee with 'one of'-condition broken

### LINKED ISSUE #4026: [Bug]: Creating a new payee as part of creating a new rule fails
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Having accidentally 'merged' a payee by applying a rule I was trying to recreate the original rule for future use. I type in the payee name for matching - this cannot automcomplete because the payee no longer exists. I selected 'Create new payee', but the payee that is created is not the one I requested, it is simply called 'new'.

### How can we reproduce the issue?

Follow the workflow as described above, or shown here:
image
Create a rule for a payee that doesn't currently exist, and click 'Create Payee' when prompted

image
Observe that the payee that gets created has the wrong name

image
Validating that it's not just a graphical glitch from a separate view

image
Observe that the same thing has been happening previously

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Mac OSX

### PR DESCRIPTION
**Pull request by sveselinovic**
Fixes #4026 

I don't think there is anything else necessary and it seems like creating a new payee with the 'one of'-operator works just fine now. I will look into it again to make sure and learn a bit more about the project. 

Should I extend/create a test for this?

### CODE REVIEW

File: packages/desktop-client/src/components/autocomplete/Autocomplete.tsx [hunk 1]
```diff
@@ -1,14 +1,14 @@
 // @ts-strict-ignore
 import React, {
```
Comment (sveselinovic) [inline packages/desktop-client/src/components/autocomplete/Autocomplete.tsx:2]: I will revert everything except the actual onAddItem-Function in a minute.

**Review by UnderKoen — APPROVED** [review]
