### PR TITLE
Fix notes icon changing size/position with long category or group names

### LINKED ISSUE #2736: [Bug]: Category Notes icon is getting encroached on
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

If a category name is long, the notes icon will move when hovering over that category.  In the flatpak build this shows up as the icon getting shrunk down when hovering.  In the regular web view the icon moves a little bit and is not lined up with other notes icons any more.

Flatpak:
image

Web view (chrome):
image

To recreate simple make a category with a long name that gets cut off with ellipses.  Then add a note to the category.  It helps to make a note on one of the neighboring categories to see the difference.

### Where are you hosting Actual?

NAS

### What browsers are you seeing the problem on?

Chrome, Desktop App (Electron)

### Operating System

Linux

### PR DESCRIPTION
**Pull request by jpelgrom**
Fixes #2736 by telling the browser this icon should not be shrunk in these rows (default is 1, which means the other icons which have `flexShrink: 0` get more space).

Before/after:

|Before (demo.actualbudget.org)|After (this branch)|
|----|----|
|image|image|
|image|image|

(first contribution, so please let me know if I missed anything)

### CODE REVIEW

File: packages/desktop-client/src/components/budget/SidebarCategory.tsx [hunk 1]
```diff
@@ -117,11 +117,13 @@ export function SidebarCategory({
...
       <View style={{ flex: 1 }} />
-      <NotesButton
-        id={category.id}
-        style={dragging && { color: 'currentColor' }}
-        defaultColor={theme.pageTextLight}
-      />
+      <View style={{ flexShrink: 0 }}>
+        <NotesButton
+          id={category.id}
+          style={dragging && { color: 'currentColor' }}
```
Comment (joel-jeremy) [inline packages/desktop-client/src/components/budget/SidebarCategory.tsx:123]: Would it work if we put the `flexShrink` in `NotesButton`'s style prop?

Comment (jpelgrom) [reply packages/desktop-client/src/components/budget/SidebarCategory.tsx:123]: No, this doesn't seem to work because the style property is applied [to the `Button`](https://github.com/actualbudget/actual/blob/f604fdaf3616d056b899ae824f97bdda476d4cee/packages/desktop-client/src/components/NotesButton.tsx#L60) which is nested too deep.

**Review by joel-jeremy — APPROVED** [review]
