### PR TITLE
:bug: (TransactionTable) fix split-transaction focus field

### LINKED ISSUE #996: [Bug]: Split Transaction Focus
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When entering a transaction that ultimately is a split you work along the transaction row until getting to the category, here you select split and the focus is moved into the split row, this happens before the amount is added in the parent row which seems incorrect. The focus should stay on the parent row until it is completed and the user move into the split once completed with entry.

### What error did you receive?

None

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by MatissJanis**
Closes #996

### CODE REVIEW

File: packages/desktop-client/src/components/accounts/TransactionsTable.js [hunk 1]
```diff
@@ -997,14 +997,14 @@ export const Transaction = React.memo(function Transaction(props) {
         name="debit"
         exposed={focusedField === 'debit'}
         focused={focusedField === 'debit'}
-        value={debit == null ? '' : debit}
```
Comment (MatissJanis) [inline packages/desktop-client/src/components/accounts/TransactionsTable.js:1000]: The `debit` and `credit` fields come from `serializeTransaction()`. If you look at how it works.. it will NEVER return these two fields as "null". Best it can do - it returns an empty string.

So fixed this check to show "0.00" value if both debit & credit is blank.

File: packages/desktop-client/src/components/accounts/TransactionsTable.js [hunk 2]
```diff
@@ -1108,7 +1108,7 @@ function makeTemporaryTransactions(currentAccountId, lastDate) {
       date: lastDate || currentDay(),
       account: currentAccountId || null,
       cleared: false,
-      amount: 0,
```
Comment (MatissJanis) [inline packages/desktop-client/src/components/accounts/TransactionsTable.js:1111]: `0` is a value that the customer can actually provide.

`null` should be the default state for new transactions - i.e. transactions with no customer input

File: packages/desktop-client/src/components/accounts/TransactionsTable.js [hunk 3]
```diff
@@ -1704,23 +1704,25 @@ export let TransactionTable = React.forwardRef((props, ref) => {
         let { data, diff } = splitTransaction(newTrans, id);
         setNewTransactions(data);
 
-        // TODO: what is this for???
```
Comment (MatissJanis) [inline packages/desktop-client/src/components/accounts/TransactionsTable.js:1707]: Well.. now we know why this was necessary :)

**Comment by rich-howell** [comment]
This resolves the issue that was reported.

File: packages/desktop-client/src/components/accounts/TransactionsTable.js (hunk 3 above)
Comment (trevdor) [reply packages/desktop-client/src/components/accounts/TransactionsTable.js:1707]: Well done. :D

**Review by trevdor — APPROVED** [review]
Nice sleuthing on this one! :shipit:
