### PR TITLE
Fix shared worker resumption after tab suspend

### LINKED ISSUE #7598: [Bug]: V26.4.0 Safari tab will become "zombie" if switch to other tabs for 1-2 mins
### What happened?

- In a normal webpage(including Actual budget prior to V26.4.0), if I switch to another tab for a couple mins and come back (Safari, no crazy add-on to put tab to sleep), the tab should still be responsive.
- After upgrading to V26.4.0, I found that the Actual Budget tab will become "zombie", entire app become unresponsive(_edit, the button is still clickable, but no data change happened after clicking_), see attached video. (There is a spinning wheel in the middle of screen outside screen recording area)
- No error in browser console

https://github.com/user-attachments/assets/9af3ec11-a27a-4cd9-91e7-cb1cfebb295d

### How can we reproduce the issue?

1. Open Actual budget in macOS Safari
2. Switch to another tab for 2mins
3. Switch back, the app is not responsive any more

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

### PR DESCRIPTION
**Pull request by jfdoming**
## Description

_Note: I used AI pretty aggressively for this PR since I wasn't familiar with this part of the codebase. I understand the architecture a bit better now as well as the solution, but very open to input on the PR since the code is not mine._

This PR fixes two bugs with multi-tab coordination that could leave tabs loading forever in certain cases.

First, in Safari, tabs are naturally suspended after a certain amount of time. When a tab is suspended, it is no longer able to keep up with heartbeats to the coordinator, which means it will be removed from the coordinator's internal state. When such a tab resumes, it uses the same `MessagePort` it was already assigned, but with no other tabs open, the coordinator wouldn't know which budget the port refers to, leaving the tab waiting forever. (This was the bug found by Claude in the other thread.) Fixed by adding explicit logic for resuming the shared worker connection, and attempting to reattach to the same budget group only if it still exists on the same port.

Second, when the leader tab is disconnected, the coordinator will fail the budget over to a new tab. In the specific scenario of a tab reload (encountered a lot during my testing), the failover process and the reloaded-tab reconnection logic occur in close succession, meaning that the reloaded tab would likely be told the backend is ready before the newly-promoted leader actually had a chance to load the budget. This meant that the reloaded tab would likely hang forever due to the connection error. Fixed by delaying the worker connect message until the new leader has actually finished loading.

## Related issue(s)

Fixes https://github.com/actualbudget/actual/issues/7598

## Testing

Would love some help testing this further! But I tested this in two ways:
(a) I found a process locally with Safari that reproduced the initial issue semi-reliably: I enabled the Safari Debug menu, then toggled "Always Suspend WebProcesses Aggressively" under "Miscellaneous Flags". (Not 100% sure this was necessary.) Then opened a bunch of tabs, unfocused the Actual window, and waited ~5 minutes. Without this PR, that reproduced the linked issue semi-reliably; with this PR, I was no longer able to reproduce.
(b) I opened two tabs next to each other, and tried various combinations of reloading the tabs and making changes. This is how I discovered the second bug, and with this PR I was no longer able to reproduce that bug.

## Checklist

- [x] Release notes added (see link above)
- [x] No obvious regressions in affected areas
- [x] Self-review has been performed - I understand what each change in the code does and why it is needed

### Bundle Stats

Bundle | Files count | Total bundle size | % Changed
------ | ----------- | ----------------- | ---------
desktop-client | 35 | 14.01 MB → 14.01 MB (+1.18 kB) | +0.01%
loot-core | 1 | 5.26 MB | 0%
api | 2 | 3.89 MB | 0%
cli | 1 | 7.97 MB | 0%
crdt | 1 | 41.83 kB | 0%

<details>
<summary>View detailed bundle stats</summary>

#### desktop-client

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
35 | 14.01 MB → 14.01 MB (+1.18 kB) | +0.01%

<details>
<summary>Changeset</summary>

File | Δ | Size
---- | - | ----
`src/browser-preload.js` | 📈 +1.18 kB (+13.79%) | 8.53 kB → 9.7 kB
</details>

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
No assets were added

**Removed**
No assets were removed

**Bigger**
Asset | File Size | % Changed
----- | --------- | ---------
static/js/index.js | 1.87 MB → 1.87 MB (+1.18 kB) | +0.06%

**Smaller**
No assets were smaller

**Unchanged**
Asset | File Size | % Changed
----- | --------- | ---------
static/js/BackgroundImage.js | 121.09 kB | 0%
static/js/FormulaEditor.js | 962.55 kB | 0%
static/js/PayeeRuleCountLabel.js | 52.52 kB | 0%
static/js/ReportRouter.js | 1.22 MB | 0%
static/js/ScheduleEditForm.js | 145.68 kB | 0%
static/js/TransactionEdit.js | 189.54 kB | 0%
static/js/TransactionList.js | 85.81 kB | 0%
static/js/Value.js | 4.94 MB | 0%
static/js/ca.js | 191.46 kB | 0%
static/js/chart-theme.js | 796.5 kB | 0%
static/js/client.js | 451.37 kB | 0%
static/js/da.js | 104.22 kB | 0%
static/js/de.js | 173.88 kB | 0%
static/js/en-GB.js | 8.2 kB | 0%
static/js/en.js | 176.89 kB | 0%
static/js/es.js | 182.3 kB | 0%
static/js/extends.js | 518.76 kB | 0%
static/js/fr.js | 182.5 kB | 0%
static/js/indexeddb-main-thread-worker-e59fee74.js | 13.46 kB | 0%
static/js/it.js | 168.33 kB | 0%
static/js/narrow.js | 364.31 kB | 0%
static/js/nb-NO.js | 151.39 kB | 0%
static/js/nl.js | 108.46 kB | 0%
static/js/pl.js | 88.14 kB | 0%
static/js/pt-BR.js | 193.24 kB | 0%
static/js/resize-observer.js | 18.06 kB | 0%
static/js/ru.js | 121.6 kB | 0%
static/js/th.js | 178.63 kB | 0%
static/js/theme.js | 31.67 kB | 0%
static/js/uk.js | 212.03 kB | 0%
static/js/useFormatList.js | 8.63 kB | 0%
static/js/wide.js | 453 B | 0%
static/js/workbox-window.prod.es5.js | 7.33 kB | 0%
static/js/zh-Hans.js | 119.88 kB | 0%
</div>
</details>

---

#### loot-core

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
1 | 5.26 MB | 0%

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
No assets were added

**Removed**
No assets were removed

**Bigger**
No assets were bigger

**Smaller**
No assets were smaller

**Unchanged**
Asset | File Size | % Changed
----- | --------- | ---------
kcab.worker.B5tkfYkU.js | 5.26 MB | 0%
</div>
</details>

---

#### api

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
2 | 3.89 MB | 0%

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
No assets were added

**Removed**
No assets were removed

**Bigger**
No assets were bigger

**Smaller**
No assets were smaller

**Unchanged**
Asset | File Size | % Changed
----- | --------- | ---------
index.js | 3.89 MB | 0%
models.js | 0 B | 0%
</div>
</details>

---

#### cli

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
1 | 7.97 MB | 0%

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
No assets were added

**Removed**
No assets were removed

**Bigger**
No assets were bigger

**Smaller**
No assets were smaller

**Unchanged**
Asset | File Size | % Changed
----- | --------- | ---------
cli.js | 7.97 MB | 0%
</div>
</details>

---

#### crdt

**Total**
Files count | Total bundle size | % Changed
----------- | ----------------- | ---------
1 | 41.83 kB | 0%

<details>
<summary>View detailed bundle breakdown</summary>
<div>

**Added**
No assets were added

**Removed**
No assets were removed

**Bigger**
No assets were bigger

**Smaller**
No assets were smaller

**Unchanged**
Asset | File Size | % Changed
----- | --------- | ---------
index.js | 41.83 kB | 0%
</div>
</details>
</details>

### CODE REVIEW

**Review by MikesGlitch — DISMISSED** [review]
Code looks fine. I don't have safari so can't test it. Works the same on chrome/firefox

File: packages/desktop-client/src/shared-browser-server-core.ts [hunk 1]
```diff
@@ -401,6 +531,14 @@ export function createCoordinator({
           return;
         }
 
+        if (msg.type === '__resume-tab') {
+          resumePort(
+            port,
+            typeof msg.budgetId === 'string' ? (msg.budgetId as string) : null,
```
Comment (MatissJanis) [inline packages/desktop-client/src/shared-browser-server-core.ts]: **💬 suggestion:** ‏do we need this?

```suggestion
            typeof msg.budgetId === 'string' ? msg.budgetId : null,
```

**Review by MatissJanis — DISMISSED** [review]
Seems to be working fine! Just one nitpick

**Review by MatissJanis — APPROVED** [review]
