### PR TITLE
Fix date validation bug causing crashes with old dates

### LINKED ISSUE #5969: [Bug]: Adding in really old dates causes the budget to crash.
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

I was doing my budget (importing CSV, adding manual transactions, reconciling the account, etc.). When I was done and wanted to return to the main budgeting screen, the error message "Something internally went wrong. You may want to restart the app if anything looks wrong. Please report this as a new issue on GitHub." appeared.
I tried the following fixes with no success:
Clear local browser cache.
Reset budget cache.
Repair transactions.

The other screens seem to work. If I attempt to switch files, the whole app becomes unresponsive (get stuck in loading forever), I have to delete the browser cache to be able to redownload the file and access it again, at which point the budget screen becomes inaccessible again.

### How can we reproduce the issue?

I do not know what caused this so I cannot say how to reproduce it.

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

### PR DESCRIPTION
**Pull request by MatissJanis**
Invalid dates should not be saved in the database. They should not cause budgets to blow up entirely. A quick fix to avoid this data corruption..

Fixes #5969

### CODE REVIEW

File: packages/loot-core/src/server/aql/schema-helpers.ts [hunk 1]
```diff
@@ -25,7 +25,7 @@ export function convertInputType(value, type) {
         return toDateRepr(dayFromDate(value));
       } else if (
         value.match(/^\d{4}-\d{2}-\d{2}$/) == null ||
-        value.date < '2000-01-01'
+        value < '2000-01-01'
```
Comment (sbrownjc) [inline packages/loot-core/src/server/aql/schema-helpers.ts:28]: Why not just try to parse it as a valid Date?
```
  var d = new Date(value);
  var dNum = d.getTime();
  if(!dNum && dNum !== 0) throw new Error('Invalid date: ' + value);
```
(code ripped from StackOverflow)

Comment (MatissJanis) [reply packages/loot-core/src/server/aql/schema-helpers.ts:28]: If we can do it with a one-liner (`value < '2000-01-01'`) - why make it more complex?

Comment (sbrownjc) [reply packages/loot-core/src/server/aql/schema-helpers.ts:28]: Maybe we want to accept valid dates older than 25 years ago?

**Review by joel-jeremy — APPROVED** [review]

File: packages/loot-core/src/server/aql/schema-helpers.ts (hunk 1 above)
Comment (MatissJanis) [reply packages/loot-core/src/server/aql/schema-helpers.ts:28]: If you have >25 years worth of transaction data in Actual - I'm pretty sure you will run into other issues more quickly than this one :)

Comment (zimmerman80) [reply packages/loot-core/src/server/aql/schema-helpers.ts:28]: I know, I know, but naturally I was trying to import a QIF/CSV from MS Money with dates as far back as 1996 and wouldn't you know I had to just set everything at 1/1/2000 because of this validation check.  The GUI will allow you to select dates before 1/1/2000, but then there is an internal server error.  

Any chance of going back another decade or so?  Or removing an unnecessary, arbitrary limitation on the software?

Comment (MatissJanis) [reply packages/loot-core/src/server/aql/schema-helpers.ts:28]: @cursor can you open a PR that changes the minimum year from 2000 to 1995?

Comment (MatissJanis) [reply packages/loot-core/src/server/aql/schema-helpers.ts:28]: @cursor try again now

Comment (MatissJanis) [reply packages/loot-core/src/server/aql/schema-helpers.ts:28]: https://github.com/actualbudget/actual/pull/6440
