### PR TITLE
:bug:  fix link-schedule option in transaction table

### LINKED ISSUE #1236: [Bug][release-blocker]: "link schedule" is broken
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Link schedule used to open in a modal. Now it opens in a new page. Thus it's broken.

Screenshot 2023-06-30 at 22 06 31

### What error did you receive?

_No response_

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

_No response_

### Operating System

None

### PR DESCRIPTION
**Pull request by MatissJanis**
Closes #1236

### CODE REVIEW

File: packages/desktop-client/src/components/accounts/Account.js [hunk 1]
```diff
@@ -641,13 +636,17 @@ function SelectedTransactionsButton({
             }
 
             if (scheduleId) {
-              navigate(`/schedule/edit/${scheduleId}`, {
+              pushModal(`/schedule/edit/${scheduleId}`, {
+                // Required in order to trigger re-renders after linking the transaction
+                // TODO: figure out a way how to remove this
                 locationPtr: location,
```
Comment (j-f1) [inline packages/desktop-client/src/components/accounts/Account.js:642]: I believe `pushModal` sets `locationPtr` automatically — were you seeing issues with doing that? Maybe there were some places still referencing `locationPtr` that need updating / we should revert `parent` back to `locationPtr`

Comment (MatissJanis) [reply packages/desktop-client/src/components/accounts/Account.js:642]: It's for this thing: https://github.com/actualbudget/actual/blob/168b38fc4befececea6af2ce0c048d96d6953ec0/packages/desktop-client/src/components/accounts/Account.js#L2083

Not a great solution IMO and something we should revisit. But I suspect this would not be a simple fix.

The issue is that we must somehow invalidate the query cache and then load fresh data in to the table when the underlying data changes (i.e. when you "link" a schedule - the transaction table should reload). But again: I suspect a proper solution here would be a lot more complex, so keeping the existing hack for now.

Comment (j-f1) [reply packages/desktop-client/src/components/accounts/Account.js:642]: → #1256

**Review by j-f1 — APPROVED** [review]
