### PR TITLE
Change Done Reconciling button text - fixes #6196

### LINKED ISSUE #6196: [Feature]: Remove extra stage from reconciliation workflow
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

Unexpected behavior of the reconcile button and inconsistent message.

### How can we reproduce the issue?

When reconciling an account, after checking the balance and clicking the "Reconcile" button, a message pops up saying "All Reconciled!" with a button saying "Done Reconciling". If at this point instead of clicking "Done Reconciling" the user navigates to a different page of Actual Budget and then navigates back to that account, the account will not actually be reconciled.

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

### PR DESCRIPTION
**Pull request by Juulz**
Changes wording of "Done reconciling" button to "Lock transactions" when _All reconciled!_, or "Exit reconciliation" if leaving unbalanced.

### CODE REVIEW

**Comment by Juulz** [comment]
I've got my fingers crossed this works. Had to pull the PR to test it!

**Comment by Juulz** [comment]
Let me know about Reconcile.test.trx  Is it used?
Only Done was changed to Exit and words added _after_ All reconciled! Not sure why the failure.

**Comment by matt-fidd** [comment]
> Let me know about Reconcile.test.trx  Is it used?
> 
> Only Done was changed to Exit and words added _after_ All reconciled! Not sure why the failure.
> 
> 

Nice job on this!

The text will need to be updated in the test file too, as it uses the content of the button to "look for it" during the test.

**Comment by Juulz** [comment]
> The text will need to be updated in the test file too, as it uses the content of the button to "look for it" during the test.

The test was failing while checking for 'All reconciled!' **getbytext** is _supposed_ to be a contains check and that line should have still worked, even with the added line below it. I changed it to the substring 'All' and it still failed the check. I then changed it to look for both lines of text together and it now passes. But... now it's ugly. I would have preferred a substring. Oh well.

**Comment by youngcw** [comment]
Im not a fan of the extra text in the done reconciling message.  At very least the spacing needs improved.  Can that information be in the docs instead of add here? The button text change is fine, I have no problem with that.

**Comment by Juulz** [comment]
I think I would actually prefer removing the extra line, and changing the button text to either 'Cancel reconciling' or 'Lock transactions'. I'm not sure I can complete that, though, if you all agree, I will try!

But, yes. The docs should hold the information and just a word change should help with folk understanding that they need to click the button.

**Comment by Juulz** [comment]
> I think I would actually prefer removing the extra line, and changing the button text to either 'Cancel reconciling' or 'Lock transactions'. I'm not sure I can complete that, though, if you all agree, I will try!

Nevermind for now. I took the extra line out and will make sure the docs are clear about what happens when you Exit.

File: packages/desktop-client/src/components/accounts/Reconcile.tsx [hunk 1]
```diff
@@ -105,7 +105,7 @@ export function ReconcilingMessage({
         )}
         <View style={{ marginLeft: 15 }}>
           <Button variant="primary" onPress={onDone}>
-            <Trans>Done reconciling</Trans>
+            <Trans>Exit reconciling</Trans>
```
Comment (youngcw) [inline packages/desktop-client/src/components/accounts/Reconcile.tsx]: What about "Finish" instead?  I think that implies that the button does something other than close the message

Comment (Juulz) [reply packages/desktop-client/src/components/accounts/Reconcile.tsx]: The problem lies in that when you click it if you _don't_ finish, nothing happens, you  just Exit - like a cancel. You don't Complete or Finish anything. I think this is why they landed on "Done", but Done is just not quite right either as it doesn't imply that a click is necessary. At least Exit lets them know they should click to leave.

Comment (Juulz) [reply packages/desktop-client/src/components/accounts/Reconcile.tsx]: I am going through the doc now. It looks like we need new screenshots for the bank sync anyway. I will scribble out some amounts and make screenshots and update the doc.

Comment (matt-fidd) [reply packages/desktop-client/src/components/accounts/Reconcile.tsx]: What about "lock transactions" which is what it actually does, or "finalise" if we want to stay with something similar to what we have now

Comment (youngcw) [reply packages/desktop-client/src/components/accounts/Reconcile.tsx]: Lock and Finalize are both good too

Comment (Juulz) [reply packages/desktop-client/src/components/accounts/Reconcile.tsx]: I really wanted to use either Complete or Lock, BUT... if you leave with an unbalanced reconcile, it does nothing - just cancels it all. Exit was about the only word my partner and I found that meant "Click me to leave this place" either way. I am putting a warning box in the docs thusly: "If you fail to click the **Exit reconciling** button after the "All reconciled!" message appears, you will not change the status of the cleared transactions to locked."

"Finalise/Finalize" means another word in the translation list LOL.

If you guys agree on a different word, I'll be happy to change out Exit for whatever you agree on. I am using this PR as a way to put my toes in the water. If you want to just leave it at "Done", at least the docs will be up to date. 

If you want different boxes for the two states, I'll have to dive deeper into the water! 

Here's a list from Theasaurus:
Exit, Leave, Quit, Close, End, Stop, Complete, Finish, Finalize

Comment (matt-fidd) [reply packages/desktop-client/src/components/accounts/Reconcile.tsx]: What about this?

```suggestion
            { targetDiff === 0 ? t('Lock transactions') : t('Exit reconciliation') }
```

Comment (Juulz) [reply packages/desktop-client/src/components/accounts/Reconcile.tsx]: Yes, please. But how about Cancel instead of Exit?

**Comment by Juulz** [comment]
I will use new screenshots to update the docs. Should be ready tomorrow.

**Comment by Juulz** [comment]
I blew up your approval when I changed the release notes, I think. 

The doc changes are done #6225. I will leave them at WIP until this change goes live.

Thanks for all the help!

File: upcoming-release-notes/6220.md [hunk 2]
```diff
@@ -0,0 +1,6 @@
+---
+category: Enhancements
+authors: [Juulz, matt-fidd]
```
Comment (matt-fidd) [inline upcoming-release-notes/6220.md:3]: Thank you for this, but don't feel like you have to include me for giving a suggestion :)

Comment (Juulz) [reply upcoming-release-notes/6220.md]: It would have taken me days to learn it! I have to learn ts now so I can be of more help. 8D
