### PR TITLE
:bug: (autocomplete) fix multi-autocomplete causing crashes

### LINKED ISSUE #2187: [Bug]: Fatal error when changing condition type for "imported payee" from "is" to "one of"
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Actualbudget fatal errors when I do the following:

- Create a rule, select `imported payee` and enter a string value for the payee (can also be done by importing transactions and creating a rule for them)
- change `is` in rule condition `imported payee` to `one of`

https://github.com/actualbudget/actual/assets/964558/dfcc0e8c-97db-41ca-9991-1b36ab6c1ed5

### What error did you receive?

Error: value can be string only if strict = false at n4 (https://domain/static/js/main.eea3298c.js:109:241670) at https://domain/static/js/main.eea3298c.js:109:246871 at Array.map (<anonymous>) at renderInput (https://domain/static/js/main.eea3298c.js:109:246857) at children (https://domain/static/js/main.eea3298c.js:109:244560) at t.e [as render] (https://domain/static/js/main.eea3298c.js:109:208466) at aJ (https://domain/static/js/main.eea3298c.js:42:79170) at aQ (https://domain/static/js/main.eea3298c.js:42:78966) at lB (https://domain/static/js/main.eea3298c.js:42:118444) at l_ (https://domain/static/js/main.eea3298c.js:42:113202)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Other

### Operating System

Mac OSX

### PR DESCRIPTION
**Pull request by MatissJanis**
Closes #2187

### CODE REVIEW

File: packages/desktop-client/src/components/autocomplete/Autocomplete.tsx [hunk 1]
```diff
@@ -31,16 +31,12 @@ function findItem<T extends Item>(
   strict: boolean,
   suggestions: T[],
   value: T | T['id'],
-): T | null {
+): T | T['id'] | null {
```
Comment (MatissJanis) [inline packages/desktop-client/src/components/autocomplete/Autocomplete.tsx:34]: Ideally I would have liked to define a type overload for this function so that if `strict: true` is used - the input value would be `T` and `strict: false` would be `T['id']`. But that's not possible due to a TS limitation

https://github.com/microsoft/TypeScript/issues/24413

**Review by joel-jeremy — APPROVED** [review]
