### PR TITLE
Update node-fetch in the API to fix connection drop issue

### LINKED ISSUE #1394: [Bug]: api can't download remote file
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I try to write a script that interacts with a remote server via `@actual/api` like described [here](https://actualbudget.org/docs/api/#connecting-to-a-remote-server).

Server version: v23.7.2
`@actual/api` version: 6.1.1

The script I use:
```
const api = require('@actual-app/api');

(async () => {
  await api.init({
    //dataDir: './',
    serverURL: '<https url to a fly VM>',
    password: '<server password>',
  });
  console.log(api);

  await api.downloadBudget('< my sync id >', { password: '< file password>' } );

  let accounts = await api.getAccounts();
	for (account in accounts) {
		console.log(account.name);
	}
  await api.shutdown();
})();
```
I execute the script via node v20.2.0.

I tried the following:
- use the budget name instead of the id --> I see an error that the sync ID can't be found
- use another password --> I see an error that the encryption password is wrong
- create a new budget file on the server, without password protection --> same error as before

### What error did you receive?

Error: Something went wrong trying to download that file, sorry! Visit https://actualbudget.org/contact/ for support. (fileId: a96b84c9-c873-41a2-9314-da454c5bc386)
    at handlers.api/download-budget (/Users/tobi/projects/actual-to-google-sheets/node_modules/@actual-app/api/dist/app/bundle.api.js:32814:31)

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Other

### Operating System

Mac OSX

### PR DESCRIPTION
**Pull request by j-f1**
We’ll now hint that the file ID might be incorrect if that’s the type of error we get.

Fixes #1394 by updating `node-fetch` (unconfirmed)

### CODE REVIEW

**Review by MatissJanis — APPROVED** [review]

**Comment by MatissJanis** [comment]
Oops.. you added the `stats.json` file.

**Comment by j-f1** [comment]
Good catch!

**Review by MatissJanis — APPROVED** [review]

**Review by toebbel — APPROVED** [review]
I can confirm that fixed connection issues to instances of actual-server running on fly.io

File: packages/api/test.js [hunk 1]
```diff
@@ -1,8 +1,9 @@
-import * as api from './index';
+let api = require('./dist/index');
```
Comment (MatissJanis) [inline packages/api/test.js:1]: Tests shouldn't rely on the compiled code, but instead the source. Any way we can change this back?

Comment (j-f1) [reply packages/api/test.js:1]: IMO this should be testing the compiled code to make sure that it actually behaves correctly. It isn’t automatically run at this point (#1074) but running directly against the source somehow could give us false confidence.

Comment (MatissJanis) [reply packages/api/test.js:1]: Actually.. this file is not even used. So I would vote to kill it off entirely.

Even when we add proper tests to api: it won't really make much sense since it's not really a unit test or a e2e test. Just some weird leftover I think.

Comment (j-f1) [reply packages/api/test.js]: 🔥

**Review by MatissJanis — APPROVED** [review]

**Comment by j-f1** [comment]
Can you do a release? (Also fine to wait if you want to do it with the other August releases)

**Comment by MatissJanis** [comment]
Lets do it with August release.
