### PR TITLE
Fix submit form on enter key pressed

### LINKED ISSUE #1582: [Bug]: Pressing Enter on Encryption Key cancels entry
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

If you type your encryption key and then press enter, the default behavior is 'Back' rather than 'Update Key'.  I think pressing enter should default to 'Update Key' and Esc should be tied to 'Back'.

image

### What error did you receive?

_No response_

### Where are you hosting Actual?

NAS

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 10

### PR DESCRIPTION
**Pull request by syukronrm**
Fix #1582 

**Root Cause**
Adding prop `type="button"` on `<Button>` doesn't work because it doesn't proparagated to HTML `<button>`.

**Changes**
- On Back button: add `isSubmit=false`.
- On Button component: Any `<Button>` with prop `type="primary"` should have be propagated as `<button type="submit">`, except if it's explicitly has prop `isSubmit=false`.

### CODE REVIEW

File: packages/desktop-client/src/components/modals/FixEncryptionKey.js [hunk 1]
```diff
@@ -127,7 +127,8 @@ export default function FixEncryptionKey({
               <Button
                 style={{ marginRight: 10 }}
                 onClick={() => modalProps.onBack()}
-                type="button"
+                type="normal"
+                isSubmit={false}
```
Comment (MatissJanis) [inline packages/desktop-client/src/components/modals/FixEncryptionKey.js:131]: **💬 suggestion:** ‏setting `isSubmit` is unnecessary here

File: packages/desktop-client/src/components/common/Button.tsx [hunk 2]
```diff
@@ -149,8 +149,9 @@ const Button = forwardRef<HTMLButtonElement, ButtonProps>(
         {...(typeof as === 'string'
           ? // eslint-disable-next-line @typescript-eslint/no-explicit-any
             (css(buttonStyle) as any)
-          : { style: buttonStyle, type: isSubmit ? 'submit' : 'button' })}
+          : { style: buttonStyle })}
         disabled={disabled}
+        type={isSubmit ? 'submit' : 'button'}
```
Comment (MatissJanis) [inline packages/desktop-client/src/components/common/Button.tsx:154]: **💭 thought:** ‏this change is unnecessary

**Review by MatissJanis — COMMENTED** [review]
The PR description does not seem to match with the code changes. Are we missing some commits? 🤔 

Also cc @shall0pass can you please verify if this fixes the bug you reported?

File: packages/desktop-client/src/components/common/Button.tsx (hunk 2 above)
Comment (MatissJanis) [reply packages/desktop-client/src/components/common/Button.tsx:154]: Never mind.. took me a while to understand this.

**Comment by shall0pass** [comment]
This works correctly for me.  Thanks!

File: packages/desktop-client/src/components/modals/FixEncryptionKey.js (hunk 1 above)
Comment (syukronrm) [reply packages/desktop-client/src/components/modals/FixEncryptionKey.js:131]: Ah yes you're right

File: packages/desktop-client/src/components/common/Button.tsx (hunk 2 above)
Comment (syukronrm) [reply packages/desktop-client/src/components/common/Button.tsx:154]: A bit confusing since we have two kind of button types; the html button and our own

File: packages/desktop-client/src/components/modals/FixEncryptionKey.js (hunk 1 above)
Comment (syukronrm) [reply packages/desktop-client/src/components/modals/FixEncryptionKey.js]: @MatissJanis updated!

**Review by MatissJanis — APPROVED** [review]

**Comment by MatissJanis** [comment]
Thanks!
