### PR TITLE
[fix] improves UX of notifications for mobile devices

### LINKED ISSUE #6539: [Bug]: excessive notifications
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

If you’re on mobile and are doing the budget, often you can quickly move down items and tap the average of x to set the budget. 

Every action triggers a notification (they are not informative notifications in my opinion) and the delay is too slow. 

This leads to multiple notifications appearing if you work fast and results in either more clicks to dismiss useless notifications or having to wait. 

Overall it’s a poor experience and we should let users disable notifications, change delay, or just remove them from this action. Ideally the notifications shouldn’t stack, they should overlap so they don’t ruin the screen experience 

Image

### How can we reproduce the issue?

Trigger multiple budget actions quickly on mobile. 

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Safari

### Operating System

Mobile Device

### PR DESCRIPTION
**Pull request by danielkerwin**
resolves #6539

### Summary
Transformed the notification system from vertical stacking to z-axis layered stacking for a more modern, space-efficient design.

### Key Changes

**Visual Design:**
- Notifications now stack on the z-axis with a "card deck" effect
- Only top 3 notifications visible (newest at front, older ones scale behind)
- Progressive scaling (5% per level), and vertical offset (-20px) for depth (opacity option provided but not used for now)
- Added 8px border radius for softer appearance
- Smooth animations when notifications are dismissed and transition forward

**Layout Improvements:**
- Repositioned close button to persistent top-right corner
- Action button now appears on the same row as message text (right-aligned)
- Better use of horizontal space

**Interactivity:**
- Only the front notification is interactive (swipe-to-dismiss)
- Background notifications have reduced pointer events
- Maintains existing swipe gesture functionality

**Configuration:**
All stacking parameters exposed as constants for easy customization:
- `MAX_VISIBLE_NOTIFICATIONS` - number of stacked notifications (default: 3)
- `SCALE_MULTIPLIER` - scale reduction per level (default: 0.05)
- `OPACITY_MULTIPLIER` - opacity reduction per level (default: 0.2)
- `MIN_OPACITY` - minimum opacity for stacked notifications (default: 1.0)
- `Y_OFFSET_PER_LEVEL` - vertical peek offset (default: -20px)
- `BASE_Z_INDEX` - base z-index for stacking (default: 10)

Screenshot 2026-01-05 at 12 15 05 pm

### CODE REVIEW

**Comment by danielkerwin** [comment]
@MatissJanis could I get a review on this one to resolve #6551

File: packages/desktop-client/src/components/Notifications.tsx [hunk 1]
```diff
@@ -91,9 +99,11 @@ function compileMessage(
 function Notification({
   notification,
   onRemove,
+  index,
```
Comment (joel-jeremy) [inline packages/desktop-client/src/components/Notifications.tsx:102]: Nit: We should use an `isSwipeable` prop instead of plain index:
```suggestion
  isSwipeable,
```

**Comment by joel-jeremy** [comment]
The new design LGTM. I'm quite unsure how to feel about the opacity change though.

Also, since the notifications are now stacked on the z-index, would it make sense for the notification auto dismiss to only apply for the top notification? Right now, all the stacked notifications are dismissed at the same time, meaning the user won't get the chance to see what the other hidden notifications were.

**Comment by danielkerwin** [comment]
> The new design LGTM. I'm quite unsure how to feel about the opacity change though.

The opacity only applies to notifications in the background of the primary - I think its a necessary effect so that the notification in the foreground has main focus and secondary notifications in the background are not blended with the first.

> Also, since the notifications are now stacked on the z-index, would it make sense for the notification auto dismiss to only apply for the top notification? Right now, all the stacked notifications are dismissed at the same time, meaning the user won't get the chance to see what the other hidden notifications were.

I think I see what you mean - I didnt change the fundamental notification system behavior, so if the "X" button previously dismissed all notifications, then it continues to do so - I think the "X" button should never have dismissed all, so I'd be happy to make that change here

**Comment by joel-jeremy** [comment]
> The opacity only applies to notifications in the background of the primary - I think its a necessary effect so that the notification in the foreground has main focus and secondary notifications in the background are not blended with the first.

Maybe a more subtle drop shadow effect would work as well?
 
> I think I see what you mean - I didnt change the fundamental notification system behavior, so if the "X" button previously dismissed all notifications, then it continues to do so - I think the "X" button should never have dismissed all, so I'd be happy to make that change here

The "x" only dismiss the specific notification not all. What I mean by auto dismiss is the notification timeout, if you don't close/swipe the notifications they will automatically be removed after 6 seconds.

https://github.com/user-attachments/assets/a8a1a65d-8605-4806-9875-2ba50237fa6e

What I'm saying is instead of the above behavior, the top notification gets auto dismissed first after it times out, then the timeout timer for the next notification starts, it gets auto dismissed, and so on.

**Comment by MatissJanis** [comment]
> What I'm saying is instead of the above behavior, the top notification gets auto dismissed first after it times out, then the timeout timer for the next notification starts, it gets auto dismissed, and so on.

Contrary to this: I think we **should** auto-dismiss all the stack after the timeout. Otherwise the stack will just live there for a very long time if users do multiple actions.

But clicking "x" directly should dismiss only one level (as already mentioned) :)

**Comment by danielkerwin** [comment]
maybe there's some confusion, because in my testing, the auto-dismiss is applied on a per-notification basis, despite what @joel-jeremy is saying that it doesn't affect all notifications

and I tend to disagree with @MatissJanis and all notifications **shouldn't** dismiss at the same time - I think the current behaviour is fine (and consistent)

perhaps we limit this PR change just to the cosmetic updates because I think right now notifications are fundamentally broken on mobile - here is another demo illustrating the auto-dismiss that applies on a per notification basis (this is the existing behavior) and a small style tweak for @joel-jeremy showing a change with no opacity (I think this is also fine).

 
Screenshot 2026-01-07 at 8 58 19 am



https://github.com/user-attachments/assets/274e37ac-b190-461e-ae1b-7421ae25acae

**Comment by joel-jeremy** [comment]
LGTM. I wouldn't want to block this PR due to that. We can always change later if needed. My only concern with auto dismissing all at once is that the user loses the chance to undo the hidden notifications. 

Can you try rebasing with master to see if that fixes the VRTs?

**Comment by danielkerwin** [comment]
> Can you try rebasing with master to see if that fixes the VRTs?

I investigated a little futher and found there was a legitimate issue with one of the mobile tests which looks for the notification text on the top-most alert, which is now the back-most alert and no longer the first alert captured by `.first()` - I refactored slightly to capture the last alert instead and its now passing locally - will see if that resolves things.

File: packages/desktop-client/src/components/Notifications.tsx (hunk 1 above)
Comment (danielkerwin) [reply packages/desktop-client/src/components/Notifications.tsx:102]: the `index` is used not only to determine where in the position of the stack the notification is, but to calculate the styles - its not replaceable with a single `isSwipeable` property and the suggestion wouldnt work here - it would need to be additive to the index which at that point im not sure the additional explicitness of interactivity is adding much value, but I've added it anyway

**Review by joel-jeremy — APPROVED** [review]

**Review by MatissJanis — APPROVED** [review]
