### PR TITLE
[Goals] fix up to only templates and negative carryover

### LINKED ISSUE #6522: [Bug]: Budget Template Simple Type "up to" variance not working as documented
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

Issue: Budget Template - Simple Type - up to variance 
Documentation indicates that if the budget starts as a negative number, the "up to" variance will fill it the "up to" amount. Eg:
Syntax:
#template up to 150 
Previous Budget:
$ -20 
Budgeted Amount:
$ 170 
New Balance:
$ 150

Actual Behavior:
Syntax:
#template up to 150 
Previous Budget (from overspending rollover):
$ -20 
Budgeted Amount:
$ 150
New Balance:
$ 130

### How can we reproduce the issue?

1. Enable Budget Template feature
2. Have a negative balance from Previous Month
3. Use "Overspending Overall" for that budget to move the negative balance to current month
4. Use "#template up to x" syntax 
5. Use "Overwrite with budget template" to current month budget

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by youngcw**
fixes #6522.

A template like `#template up to 150` should get the category balance up to 150 no matter how much was rolled forward, even if it was a negative amount.

### CODE REVIEW

File: packages/loot-core/src/server/budget/category-template-context.ts [hunk 1]
```diff
@@ -548,7 +548,7 @@ export class CategoryTemplateContext {
         templateContext.currency.decimalPlaces,
       );
     } else {
-      return templateContext.limitAmount;
+      return templateContext.limitAmount - templateContext.fromLastMonth;
```
Comment (youngcw) [inline packages/loot-core/src/server/budget/category-template-context.ts:551]: This is a complete solution and works for all cases of funds carried over.  Previously the case of positive funds carried forward was handled by the category level limit check, but now all cases are directly handled here.

**Review by joel-jeremy — APPROVED** [review]
